"""Verify the exported ONNX model reproduces the committed reference embeddings.

Runs in the Docker ``test`` stage. The reference vectors were generated by
generate_reference.py with sentence-transformers (PyTorch); the ONNX export must
match them per-vector within the stated tolerance, and every ONNX vector must be
unit-length. A failure here means the export drifted and must not ship.
"""

import json
from pathlib import Path

import numpy as np
import onnxruntime as ort
import pytest
import tokenizers

MODEL_DIR = Path("/opt/model")
MAX_SEQ_LENGTH = 128
MAX_ABS_DIFF = 1e-3
MIN_COSINE = 0.9999
MAX_NORM_DRIFT = 1e-4

_REFERENCE = json.loads((Path(__file__).parent / "testdata" / "reference_embeddings.json").read_text())
_TEXTS = _REFERENCE["texts"]
_REFERENCE_VECTORS = np.array(_REFERENCE["vectors"], dtype=np.float32)

_session_options = ort.SessionOptions()
_session_options.intra_op_num_threads = 2
_session = ort.InferenceSession(
    str(MODEL_DIR / "model.onnx"),
    providers=["CPUExecutionProvider"],
    sess_options=_session_options,
)
_tokenizer = tokenizers.Tokenizer.from_file(str(MODEL_DIR / "tokenizer.json"))
_tokenizer.enable_truncation(max_length=MAX_SEQ_LENGTH)
_tokenizer.enable_padding(length=None, pad_id=0, pad_token="[PAD]")


def _embed(texts):
    encoded = _tokenizer.encode_batch(texts)
    input_ids = np.array([e.ids for e in encoded], dtype=np.int64)
    attention_mask = np.array([e.attention_mask for e in encoded], dtype=np.int64)
    # The ONNX export bundles the sentence-transformers Pooling module, so
    # output[1] (sentence_embedding) is already mean-pooled; we only normalize.
    outputs = _session.run(
        None,
        {"input_ids": input_ids, "attention_mask": attention_mask},
    )
    sentence_embedding = outputs[1]
    norms = np.linalg.norm(sentence_embedding, axis=1, keepdims=True)
    norms[norms == 0] = 1.0
    return sentence_embedding / norms

@pytest.fixture(scope="module")
def onnx_vectors():
    return _embed(_TEXTS).astype(np.float32)

def test_onnx_matches_reference_within_tolerance(onnx_vectors):
    diffs = np.abs(onnx_vectors - _REFERENCE_VECTORS)
    assert diffs.max() <= MAX_ABS_DIFF, f"max abs diff {diffs.max()} exceeds {MAX_ABS_DIFF}"


def test_onnx_matches_reference_cosine(onnx_vectors):
    cosines = np.sum(onnx_vectors * _REFERENCE_VECTORS, axis=1)
    worst = cosines.min()
    assert worst >= MIN_COSINE, f"worst cosine {worst} below {MIN_COSINE}"


def test_onnx_vectors_are_unit_length(onnx_vectors):
    norms = np.linalg.norm(onnx_vectors, axis=1)
    drift = np.abs(norms - 1.0).max()
    assert drift <= MAX_NORM_DRIFT, f"unit-norm drift {drift} exceeds {MAX_NORM_DRIFT}"
