// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ErrorCode.
const (
	ErrorCodeInternal        ErrorCode = "internal_error"
	ErrorCodeInvalidJSON     ErrorCode = "invalid_json"
	ErrorCodeInvalidNote     ErrorCode = "invalid_note"
	ErrorCodeInvalidSearch   ErrorCode = "invalid_search"
	ErrorCodeNotFound        ErrorCode = "not_found"
	ErrorCodeRequestTooLarge ErrorCode = "request_too_large"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ErrorCodeInternal:
		return true
	case ErrorCodeInvalidJSON:
		return true
	case ErrorCodeInvalidNote:
		return true
	case ErrorCodeInvalidSearch:
		return true
	case ErrorCodeNotFound:
		return true
	case ErrorCodeRequestTooLarge:
		return true
	default:
		return false
	}
}

// Defines values for ValidationField.
const (
	ValidationFieldBody         ValidationField = "body"
	ValidationFieldCategorySlug ValidationField = "category_slug"
	ValidationFieldCitySlug     ValidationField = "city_slug"
	ValidationFieldQ            ValidationField = "q"
	ValidationFieldTitle        ValidationField = "title"
)

// Valid indicates whether the value is a known member of the ValidationField enum.
func (e ValidationField) Valid() bool {
	switch e {
	case ValidationFieldBody:
		return true
	case ValidationFieldCategorySlug:
		return true
	case ValidationFieldCitySlug:
		return true
	case ValidationFieldQ:
		return true
	case ValidationFieldTitle:
		return true
	default:
		return false
	}
}

// Defines values for ValidationProblemCode.
const (
	ValidationProblemCodeRequired ValidationProblemCode = "required"
	ValidationProblemCodeTooLong  ValidationProblemCode = "too_long"
	ValidationProblemCodeTooShort ValidationProblemCode = "too_short"
	ValidationProblemCodeUnknown  ValidationProblemCode = "unknown"
)

// Valid indicates whether the value is a known member of the ValidationProblemCode enum.
func (e ValidationProblemCode) Valid() bool {
	switch e {
	case ValidationProblemCodeRequired:
		return true
	case ValidationProblemCodeTooLong:
		return true
	case ValidationProblemCodeTooShort:
		return true
	case ValidationProblemCodeUnknown:
		return true
	default:
		return false
	}
}

// CategorySlug defines model for CategorySlug.
type CategorySlug = string

// CitySlug defines model for CitySlug.
type CitySlug = string

// CreateNoteRequest defines model for CreateNoteRequest.
type CreateNoteRequest struct {
	Body         string       `json:"body"`
	CategorySlug CategorySlug `json:"category_slug"`
	CitySlug     CitySlug     `json:"city_slug"`
	Title        string       `json:"title"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code   ErrorCode            `json:"code"`
	Fields *[]ValidationProblem `json:"fields,omitempty"`
}

// ListNotesResponse defines model for ListNotesResponse.
type ListNotesResponse struct {
	Notes []Note `json:"notes"`
}

// Note defines model for Note.
type Note struct {
	Body         string       `json:"body"`
	CategorySlug CategorySlug `json:"category_slug"`
	CitySlug     CitySlug     `json:"city_slug"`

	// CreatedAt Unix timestamp in milliseconds.
	CreatedAt int64  `json:"created_at"`
	Id        string `json:"id"`
	Title     string `json:"title"`

	// UpdatedAt Unix timestamp in milliseconds.
	UpdatedAt int64 `json:"updated_at"`
}

// ValidationField defines model for ValidationField.
type ValidationField string

// ValidationProblem defines model for ValidationProblem.
type ValidationProblem struct {
	Code  ValidationProblemCode `json:"code"`
	Field ValidationField       `json:"field"`
}

// ValidationProblemCode defines model for ValidationProblem.Code.
type ValidationProblemCode string

// SearchNotesParams defines parameters for SearchNotes.
type SearchNotesParams struct {
	// Q Raw user search text. Missing, blank, or overlong values return invalid_search.
	Q *string `form:"q,omitempty" json:"q,omitempty"`
}

// CreateNoteJSONRequestBody defines body for CreateNote for application/json ContentType.
type CreateNoteJSONRequestBody = CreateNoteRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Check process health
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Check API readiness
	// (GET /readyz)
	GetReadiness(w http.ResponseWriter, r *http.Request)
	// List recent notes
	// (GET /v1/notes)
	ListNotes(w http.ResponseWriter, r *http.Request)
	// Create a note
	// (POST /v1/notes)
	CreateNote(w http.ResponseWriter, r *http.Request)
	// Get a note
	// (GET /v1/notes/{note_id})
	GetNote(w http.ResponseWriter, r *http.Request, noteId string)
	// Search notes
	// (GET /v1/search/notes)
	SearchNotes(w http.ResponseWriter, r *http.Request, params SearchNotesParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Check process health
// (GET /healthz)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Check API readiness
// (GET /readyz)
func (_ Unimplemented) GetReadiness(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List recent notes
// (GET /v1/notes)
func (_ Unimplemented) ListNotes(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a note
// (POST /v1/notes)
func (_ Unimplemented) CreateNote(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a note
// (GET /v1/notes/{note_id})
func (_ Unimplemented) GetNote(w http.ResponseWriter, r *http.Request, noteId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Search notes
// (GET /v1/search/notes)
func (_ Unimplemented) SearchNotes(w http.ResponseWriter, r *http.Request, params SearchNotesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadiness operation middleware
func (siw *ServerInterfaceWrapper) GetReadiness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadiness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListNotes operation middleware
func (siw *ServerInterfaceWrapper) ListNotes(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListNotes(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateNote operation middleware
func (siw *ServerInterfaceWrapper) CreateNote(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateNote(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetNote operation middleware
func (siw *ServerInterfaceWrapper) GetNote(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "note_id" -------------
	var noteId string

	err = runtime.BindStyledParameterWithOptions("simple", "note_id", chi.URLParam(r, "note_id"), &noteId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "note_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetNote(w, r, noteId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchNotes operation middleware
func (siw *ServerInterfaceWrapper) SearchNotes(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchNotesParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchNotes(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/readyz", wrapper.GetReadiness)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/notes", wrapper.ListNotes)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/notes", wrapper.CreateNote)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/notes/{note_id}", wrapper.GetNote)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/search/notes", wrapper.SearchNotes)
	})

	return r
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth204Response struct {
}

func (response GetHealth204Response) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type GetHealth400JSONResponse ErrorResponse

func (response GetHealth400JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadinessRequestObject struct {
}

type GetReadinessResponseObject interface {
	VisitGetReadinessResponse(w http.ResponseWriter) error
}

type GetReadiness204Response struct {
}

func (response GetReadiness204Response) VisitGetReadinessResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type GetReadiness400JSONResponse ErrorResponse

func (response GetReadiness400JSONResponse) VisitGetReadinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListNotesRequestObject struct {
}

type ListNotesResponseObject interface {
	VisitListNotesResponse(w http.ResponseWriter) error
}

type ListNotes200JSONResponse ListNotesResponse

func (response ListNotes200JSONResponse) VisitListNotesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListNotes400JSONResponse ErrorResponse

func (response ListNotes400JSONResponse) VisitListNotesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListNotes500JSONResponse ErrorResponse

func (response ListNotes500JSONResponse) VisitListNotesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateNoteRequestObject struct {
	Body *CreateNoteJSONRequestBody
}

type CreateNoteResponseObject interface {
	VisitCreateNoteResponse(w http.ResponseWriter) error
}

type CreateNote201JSONResponse Note

func (response CreateNote201JSONResponse) VisitCreateNoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateNote400JSONResponse ErrorResponse

func (response CreateNote400JSONResponse) VisitCreateNoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateNote413JSONResponse ErrorResponse

func (response CreateNote413JSONResponse) VisitCreateNoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type CreateNote500JSONResponse ErrorResponse

func (response CreateNote500JSONResponse) VisitCreateNoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetNoteRequestObject struct {
	NoteId string `json:"note_id"`
}

type GetNoteResponseObject interface {
	VisitGetNoteResponse(w http.ResponseWriter) error
}

type GetNote200JSONResponse Note

func (response GetNote200JSONResponse) VisitGetNoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetNote400JSONResponse ErrorResponse

func (response GetNote400JSONResponse) VisitGetNoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetNote404JSONResponse ErrorResponse

func (response GetNote404JSONResponse) VisitGetNoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetNote500JSONResponse ErrorResponse

func (response GetNote500JSONResponse) VisitGetNoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type SearchNotesRequestObject struct {
	Params SearchNotesParams
}

type SearchNotesResponseObject interface {
	VisitSearchNotesResponse(w http.ResponseWriter) error
}

type SearchNotes200JSONResponse ListNotesResponse

func (response SearchNotes200JSONResponse) VisitSearchNotesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SearchNotes400JSONResponse ErrorResponse

func (response SearchNotes400JSONResponse) VisitSearchNotesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type SearchNotes500JSONResponse ErrorResponse

func (response SearchNotes500JSONResponse) VisitSearchNotesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Check process health
	// (GET /healthz)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// Check API readiness
	// (GET /readyz)
	GetReadiness(ctx context.Context, request GetReadinessRequestObject) (GetReadinessResponseObject, error)
	// List recent notes
	// (GET /v1/notes)
	ListNotes(ctx context.Context, request ListNotesRequestObject) (ListNotesResponseObject, error)
	// Create a note
	// (POST /v1/notes)
	CreateNote(ctx context.Context, request CreateNoteRequestObject) (CreateNoteResponseObject, error)
	// Get a note
	// (GET /v1/notes/{note_id})
	GetNote(ctx context.Context, request GetNoteRequestObject) (GetNoteResponseObject, error)
	// Search notes
	// (GET /v1/search/notes)
	SearchNotes(ctx context.Context, request SearchNotesRequestObject) (SearchNotesResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReadiness operation middleware
func (sh *strictHandler) GetReadiness(w http.ResponseWriter, r *http.Request) {
	var request GetReadinessRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetReadiness(ctx, request.(GetReadinessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReadiness")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetReadinessResponseObject); ok {
		if err := validResponse.VisitGetReadinessResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListNotes operation middleware
func (sh *strictHandler) ListNotes(w http.ResponseWriter, r *http.Request) {
	var request ListNotesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListNotes(ctx, request.(ListNotesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListNotes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListNotesResponseObject); ok {
		if err := validResponse.VisitListNotesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateNote operation middleware
func (sh *strictHandler) CreateNote(w http.ResponseWriter, r *http.Request) {
	var request CreateNoteRequestObject

	var body CreateNoteJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateNote(ctx, request.(CreateNoteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateNote")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateNoteResponseObject); ok {
		if err := validResponse.VisitCreateNoteResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetNote operation middleware
func (sh *strictHandler) GetNote(w http.ResponseWriter, r *http.Request, noteId string) {
	var request GetNoteRequestObject

	request.NoteId = noteId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetNote(ctx, request.(GetNoteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetNote")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetNoteResponseObject); ok {
		if err := validResponse.VisitGetNoteResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SearchNotes operation middleware
func (sh *strictHandler) SearchNotes(w http.ResponseWriter, r *http.Request, params SearchNotesParams) {
	var request SearchNotesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SearchNotes(ctx, request.(SearchNotesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchNotes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SearchNotesResponseObject); ok {
		if err := validResponse.VisitSearchNotesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1FhNc9s2EP0rGLRHRpITtwfeEjcf7jiOazu9ZDwamFyRSEiABpaKVY/+e2cBkKJI2pYzqe2eJOJr3z68",
	"XSxwwxNdVlqBQsvjG26THErh/h4IhEyb1VlRZ/SNqwp4zC0aqTK+jviBxDs6DQiEY41wClc1WKRRIk0l",
	"Sq1EcWJ0BQYlWB4vRGEh4lWn6YZf6nRFv6W4PgKVYc7j/dlsFvFSqqZhLxraTQLquQ3IfjWw4DH/Zbpx",
	"dBq8nG65SJMl7jixcX0dcZRYQA/q3sv7kK4jbuCqlgZSHn8Ji0Te7b4XXWAX7Ur68iskSAjeGqPNgU4d",
	"ClB1SStKhWCUKOZAvTziUi1FIdP5V6tV51NphM6nBWGSnEdcaZwvdK1S7pGCxTlqPS+EyaADIzgU8esX",
	"ZPrFUhglStrELxtghwEMj7ptzuKfZ5+OR5qPPax+81kDr+041vguwGzbguTOtT7yaBuSTsFWWll4oBiT",
	"wO1dkthswjriCwlF6qZKhNLeN/dvck0QmBOjLwsona48v8IYsRroxSEa08KRtEjc2R90leSwO3C3S/dh",
	"9UuOgXXTfywvPIPAT1yKS+fC5bYUbGJkRW7wmH9W8pqhLMGiKCsmFStlUUgLiVapnfCIL7QpaSYF6u/7",
	"3KULWVLszlqmKIYzMGRMpqNet8ln0FNX6WOh6+23pFjcOaFt8bgFe0wxm0h5RyHWTXgPsHi1Y/7qWTsP",
	"FnrNb7zBXuuWxIa9jY4GPX+5bDXMCD+WsRpy2v2JOCVxm2uD4X+hnfu1+qb0d/VgZgK+Ju0GI6P951qf",
	"BcO39R95MKPdnxuETYLdPa16sfSF6heJbkumNFyqhR7Gz4fz8xNGBxdLtEIjEmQLbRjmwGyaWvb65JCC",
	"qJAJhAxMxFHgHR8dHrw9Pnv7BzFuCh7zHLGy8XRqq/R6ok02DbPsdDN4kmNZdMKdN1Z4xJdgrEc1m8wm",
	"MxqlK1CikjzmryazySse8Upg7nQxzUEUmP9D/zNwqYFk40g6THnM3wN+cEPcse+PEDfz5Wx/SMR5DgSD",
	"VUYnYC2TlplaKamyCQHZn828GBWC8hVgVRUyceamrhBpa86dztf2UHObM8QSChWWarBMaWSlwCR3G0Mw",
	"m92aOCnYuiyFWfGYH+SQfGudyBv/UWRO7J8ahiy/oIlTAyJd3cnhKYhUKrD2QTQmQjELZgkMjVgsZPI/",
	"ZJFGmI73t5K43Ju2xcYojW0pM+Tw5xEyrJdGSDmFBBQyB/e5b0nEf3tscB5BXaQOWSHthqotgRDXzHS4",
	"7MjDbzSl9krbETFs7pOb+8ibUAv+FE+HF9b19nmBpob1QIl7Pw2Ar6XHGSa22HdhWaiVnlaE7uTTxqMK",
	"5in1hzukB7f36mnAUflHYFBr5u6qzyEm/La5cCXSBpnTdwsWLuP9oOimy+kN/cxlur7r/AmBUgkjSkAw",
	"tNwNl4SOagG63/uKJCzG+0qPOmT0ny4u/sN8fF8UPP/0u+9P+McD1yYHAuaebJ6D5DPAW/X+HvBesfuH",
	"qHtKBP8c1BQJPbX3znDxndUWDPMLM4RrnLCP0lqpsohdFkJ9iyir6SUYuhOxpShqsMwA1kax7QeyiXsy",
	"4zG/qsGsNuF0xZ8qcHYqZD6SbKXKnrKUCfw74vqnxhNrNkAbLV7OOn1jqqXBVLqPiu91gnLprWkjM6na",
	"69+UkyrCagPN1gplCeFGwkCllZYK3QtNEFynrF5Hg3sFXOOLhTS+7NJlCcrfhxsX22W8G+uL9b8BAAD/",
	"/w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
