// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ErrorCode.
const (
	ErrorCodeInternal        ErrorCode = "internal_error"
	ErrorCodeInvalidJSON     ErrorCode = "invalid_json"
	ErrorCodeInvalidNote     ErrorCode = "invalid_note"
	ErrorCodeInvalidSearch   ErrorCode = "invalid_search"
	ErrorCodeNotFound        ErrorCode = "not_found"
	ErrorCodeRequestTooLarge ErrorCode = "request_too_large"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ErrorCodeInternal:
		return true
	case ErrorCodeInvalidJSON:
		return true
	case ErrorCodeInvalidNote:
		return true
	case ErrorCodeInvalidSearch:
		return true
	case ErrorCodeNotFound:
		return true
	case ErrorCodeRequestTooLarge:
		return true
	default:
		return false
	}
}

// Defines values for ValidationField.
const (
	ValidationFieldBody         ValidationField = "body"
	ValidationFieldCategorySlug ValidationField = "category_slug"
	ValidationFieldPlaceSlug    ValidationField = "place_slug"
	ValidationFieldQ            ValidationField = "q"
	ValidationFieldTitle        ValidationField = "title"
)

// Valid indicates whether the value is a known member of the ValidationField enum.
func (e ValidationField) Valid() bool {
	switch e {
	case ValidationFieldBody:
		return true
	case ValidationFieldCategorySlug:
		return true
	case ValidationFieldPlaceSlug:
		return true
	case ValidationFieldQ:
		return true
	case ValidationFieldTitle:
		return true
	default:
		return false
	}
}

// Defines values for ValidationProblemCode.
const (
	ValidationProblemCodeRequired ValidationProblemCode = "required"
	ValidationProblemCodeTooLong  ValidationProblemCode = "too_long"
	ValidationProblemCodeTooShort ValidationProblemCode = "too_short"
	ValidationProblemCodeUnknown  ValidationProblemCode = "unknown"
)

// Valid indicates whether the value is a known member of the ValidationProblemCode enum.
func (e ValidationProblemCode) Valid() bool {
	switch e {
	case ValidationProblemCodeRequired:
		return true
	case ValidationProblemCodeTooLong:
		return true
	case ValidationProblemCodeTooShort:
		return true
	case ValidationProblemCodeUnknown:
		return true
	default:
		return false
	}
}

// CatalogCategory defines model for CatalogCategory.
type CatalogCategory struct {
	Active       bool         `json:"active"`
	DisplayOrder int32        `json:"display_order"`
	Label        string       `json:"label"`
	Slug         CategorySlug `json:"slug"`
}

// CatalogPlace defines model for CatalogPlace.
type CatalogPlace struct {
	Active       bool      `json:"active"`
	DisplayOrder int32     `json:"display_order"`
	Label        string    `json:"label"`
	Slug         PlaceSlug `json:"slug"`
}

// CategorySlug defines model for CategorySlug.
type CategorySlug = string

// CreateNoteRequest defines model for CreateNoteRequest.
type CreateNoteRequest struct {
	Body         string       `json:"body"`
	CategorySlug CategorySlug `json:"category_slug"`
	PlaceSlug    *PlaceSlug   `json:"place_slug,omitempty"`
	Title        string       `json:"title"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code   ErrorCode            `json:"code"`
	Fields *[]ValidationProblem `json:"fields,omitempty"`
}

// ListCategoriesResponse defines model for ListCategoriesResponse.
type ListCategoriesResponse struct {
	Categories []CatalogCategory `json:"categories"`
}

// ListNotesResponse defines model for ListNotesResponse.
type ListNotesResponse struct {
	Notes []Note `json:"notes"`
}

// ListPlacesResponse defines model for ListPlacesResponse.
type ListPlacesResponse struct {
	Places []CatalogPlace `json:"places"`
}

// Note defines model for Note.
type Note struct {
	Body         string       `json:"body"`
	CategorySlug CategorySlug `json:"category_slug"`

	// CreatedAt Unix timestamp in milliseconds.
	CreatedAt int64      `json:"created_at"`
	Id        string     `json:"id"`
	PlaceSlug *PlaceSlug `json:"place_slug"`
	Title     string     `json:"title"`

	// UpdatedAt Unix timestamp in milliseconds.
	UpdatedAt int64 `json:"updated_at"`
}

// PlaceSlug defines model for PlaceSlug.
type PlaceSlug = string

// ValidationField defines model for ValidationField.
type ValidationField string

// ValidationProblem defines model for ValidationProblem.
type ValidationProblem struct {
	Code  ValidationProblemCode `json:"code"`
	Field ValidationField       `json:"field"`
}

// ValidationProblemCode defines model for ValidationProblem.Code.
type ValidationProblemCode string

// ListNotesParams defines parameters for ListNotes.
type ListNotesParams struct {
	// CategorySlug Optional active category slug used to narrow recent notes.
	CategorySlug *CategorySlug `form:"category_slug,omitempty" json:"category_slug,omitempty"`
}

// SearchNotesParams defines parameters for SearchNotes.
type SearchNotesParams struct {
	// Q Raw user search text. Missing, blank, or overlong values return invalid_search.
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// CategorySlug Optional active category slug used to narrow search results.
	CategorySlug *CategorySlug `form:"category_slug,omitempty" json:"category_slug,omitempty"`
}

// CreateNoteJSONRequestBody defines body for CreateNote for application/json ContentType.
type CreateNoteJSONRequestBody = CreateNoteRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Check process health
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Check API readiness
	// (GET /readyz)
	GetReadiness(w http.ResponseWriter, r *http.Request)
	// List category catalog
	// (GET /v1/categories)
	ListCategories(w http.ResponseWriter, r *http.Request)
	// List recent notes
	// (GET /v1/notes)
	ListNotes(w http.ResponseWriter, r *http.Request, params ListNotesParams)
	// Create a note
	// (POST /v1/notes)
	CreateNote(w http.ResponseWriter, r *http.Request)
	// Get a note
	// (GET /v1/notes/{note_id})
	GetNote(w http.ResponseWriter, r *http.Request, noteId string)
	// List place catalog
	// (GET /v1/places)
	ListPlaces(w http.ResponseWriter, r *http.Request)
	// Search notes
	// (GET /v1/search/notes)
	SearchNotes(w http.ResponseWriter, r *http.Request, params SearchNotesParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Check process health
// (GET /healthz)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Check API readiness
// (GET /readyz)
func (_ Unimplemented) GetReadiness(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List category catalog
// (GET /v1/categories)
func (_ Unimplemented) ListCategories(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List recent notes
// (GET /v1/notes)
func (_ Unimplemented) ListNotes(w http.ResponseWriter, r *http.Request, params ListNotesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a note
// (POST /v1/notes)
func (_ Unimplemented) CreateNote(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a note
// (GET /v1/notes/{note_id})
func (_ Unimplemented) GetNote(w http.ResponseWriter, r *http.Request, noteId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List place catalog
// (GET /v1/places)
func (_ Unimplemented) ListPlaces(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Search notes
// (GET /v1/search/notes)
func (_ Unimplemented) SearchNotes(w http.ResponseWriter, r *http.Request, params SearchNotesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadiness operation middleware
func (siw *ServerInterfaceWrapper) GetReadiness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadiness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCategories operation middleware
func (siw *ServerInterfaceWrapper) ListCategories(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCategories(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListNotes operation middleware
func (siw *ServerInterfaceWrapper) ListNotes(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListNotesParams

	// ------------- Optional query parameter "category_slug" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "category_slug", r.URL.Query(), &params.CategorySlug, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "category_slug"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "category_slug", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListNotes(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateNote operation middleware
func (siw *ServerInterfaceWrapper) CreateNote(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateNote(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetNote operation middleware
func (siw *ServerInterfaceWrapper) GetNote(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "note_id" -------------
	var noteId string

	err = runtime.BindStyledParameterWithOptions("simple", "note_id", chi.URLParam(r, "note_id"), &noteId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "note_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetNote(w, r, noteId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPlaces operation middleware
func (siw *ServerInterfaceWrapper) ListPlaces(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPlaces(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchNotes operation middleware
func (siw *ServerInterfaceWrapper) SearchNotes(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchNotesParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "category_slug" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "category_slug", r.URL.Query(), &params.CategorySlug, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "category_slug"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "category_slug", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchNotes(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/readyz", wrapper.GetReadiness)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/categories", wrapper.ListCategories)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/notes", wrapper.ListNotes)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/notes", wrapper.CreateNote)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/notes/{note_id}", wrapper.GetNote)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/places", wrapper.ListPlaces)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/search/notes", wrapper.SearchNotes)
	})

	return r
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth204Response struct {
}

func (response GetHealth204Response) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type GetHealth400JSONResponse ErrorResponse

func (response GetHealth400JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadinessRequestObject struct {
}

type GetReadinessResponseObject interface {
	VisitGetReadinessResponse(w http.ResponseWriter) error
}

type GetReadiness204Response struct {
}

func (response GetReadiness204Response) VisitGetReadinessResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type GetReadiness400JSONResponse ErrorResponse

func (response GetReadiness400JSONResponse) VisitGetReadinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListCategoriesRequestObject struct {
}

type ListCategoriesResponseObject interface {
	VisitListCategoriesResponse(w http.ResponseWriter) error
}

type ListCategories200JSONResponse ListCategoriesResponse

func (response ListCategories200JSONResponse) VisitListCategoriesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListCategories400JSONResponse ErrorResponse

func (response ListCategories400JSONResponse) VisitListCategoriesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListCategories500JSONResponse ErrorResponse

func (response ListCategories500JSONResponse) VisitListCategoriesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListNotesRequestObject struct {
	Params ListNotesParams
}

type ListNotesResponseObject interface {
	VisitListNotesResponse(w http.ResponseWriter) error
}

type ListNotes200JSONResponse ListNotesResponse

func (response ListNotes200JSONResponse) VisitListNotesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListNotes400JSONResponse ErrorResponse

func (response ListNotes400JSONResponse) VisitListNotesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListNotes500JSONResponse ErrorResponse

func (response ListNotes500JSONResponse) VisitListNotesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateNoteRequestObject struct {
	Body *CreateNoteJSONRequestBody
}

type CreateNoteResponseObject interface {
	VisitCreateNoteResponse(w http.ResponseWriter) error
}

type CreateNote201JSONResponse Note

func (response CreateNote201JSONResponse) VisitCreateNoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateNote400JSONResponse ErrorResponse

func (response CreateNote400JSONResponse) VisitCreateNoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateNote413JSONResponse ErrorResponse

func (response CreateNote413JSONResponse) VisitCreateNoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type CreateNote500JSONResponse ErrorResponse

func (response CreateNote500JSONResponse) VisitCreateNoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetNoteRequestObject struct {
	NoteId string `json:"note_id"`
}

type GetNoteResponseObject interface {
	VisitGetNoteResponse(w http.ResponseWriter) error
}

type GetNote200JSONResponse Note

func (response GetNote200JSONResponse) VisitGetNoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetNote400JSONResponse ErrorResponse

func (response GetNote400JSONResponse) VisitGetNoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetNote404JSONResponse ErrorResponse

func (response GetNote404JSONResponse) VisitGetNoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetNote500JSONResponse ErrorResponse

func (response GetNote500JSONResponse) VisitGetNoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListPlacesRequestObject struct {
}

type ListPlacesResponseObject interface {
	VisitListPlacesResponse(w http.ResponseWriter) error
}

type ListPlaces200JSONResponse ListPlacesResponse

func (response ListPlaces200JSONResponse) VisitListPlacesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListPlaces400JSONResponse ErrorResponse

func (response ListPlaces400JSONResponse) VisitListPlacesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListPlaces500JSONResponse ErrorResponse

func (response ListPlaces500JSONResponse) VisitListPlacesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type SearchNotesRequestObject struct {
	Params SearchNotesParams
}

type SearchNotesResponseObject interface {
	VisitSearchNotesResponse(w http.ResponseWriter) error
}

type SearchNotes200JSONResponse ListNotesResponse

func (response SearchNotes200JSONResponse) VisitSearchNotesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SearchNotes400JSONResponse ErrorResponse

func (response SearchNotes400JSONResponse) VisitSearchNotesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type SearchNotes500JSONResponse ErrorResponse

func (response SearchNotes500JSONResponse) VisitSearchNotesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Check process health
	// (GET /healthz)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// Check API readiness
	// (GET /readyz)
	GetReadiness(ctx context.Context, request GetReadinessRequestObject) (GetReadinessResponseObject, error)
	// List category catalog
	// (GET /v1/categories)
	ListCategories(ctx context.Context, request ListCategoriesRequestObject) (ListCategoriesResponseObject, error)
	// List recent notes
	// (GET /v1/notes)
	ListNotes(ctx context.Context, request ListNotesRequestObject) (ListNotesResponseObject, error)
	// Create a note
	// (POST /v1/notes)
	CreateNote(ctx context.Context, request CreateNoteRequestObject) (CreateNoteResponseObject, error)
	// Get a note
	// (GET /v1/notes/{note_id})
	GetNote(ctx context.Context, request GetNoteRequestObject) (GetNoteResponseObject, error)
	// List place catalog
	// (GET /v1/places)
	ListPlaces(ctx context.Context, request ListPlacesRequestObject) (ListPlacesResponseObject, error)
	// Search notes
	// (GET /v1/search/notes)
	SearchNotes(ctx context.Context, request SearchNotesRequestObject) (SearchNotesResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReadiness operation middleware
func (sh *strictHandler) GetReadiness(w http.ResponseWriter, r *http.Request) {
	var request GetReadinessRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetReadiness(ctx, request.(GetReadinessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReadiness")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetReadinessResponseObject); ok {
		if err := validResponse.VisitGetReadinessResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListCategories operation middleware
func (sh *strictHandler) ListCategories(w http.ResponseWriter, r *http.Request) {
	var request ListCategoriesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListCategories(ctx, request.(ListCategoriesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListCategories")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListCategoriesResponseObject); ok {
		if err := validResponse.VisitListCategoriesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListNotes operation middleware
func (sh *strictHandler) ListNotes(w http.ResponseWriter, r *http.Request, params ListNotesParams) {
	var request ListNotesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListNotes(ctx, request.(ListNotesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListNotes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListNotesResponseObject); ok {
		if err := validResponse.VisitListNotesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateNote operation middleware
func (sh *strictHandler) CreateNote(w http.ResponseWriter, r *http.Request) {
	var request CreateNoteRequestObject

	var body CreateNoteJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateNote(ctx, request.(CreateNoteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateNote")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateNoteResponseObject); ok {
		if err := validResponse.VisitCreateNoteResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetNote operation middleware
func (sh *strictHandler) GetNote(w http.ResponseWriter, r *http.Request, noteId string) {
	var request GetNoteRequestObject

	request.NoteId = noteId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetNote(ctx, request.(GetNoteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetNote")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetNoteResponseObject); ok {
		if err := validResponse.VisitGetNoteResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListPlaces operation middleware
func (sh *strictHandler) ListPlaces(w http.ResponseWriter, r *http.Request) {
	var request ListPlacesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListPlaces(ctx, request.(ListPlacesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListPlaces")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListPlacesResponseObject); ok {
		if err := validResponse.VisitListPlacesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SearchNotes operation middleware
func (sh *strictHandler) SearchNotes(w http.ResponseWriter, r *http.Request, params SearchNotesParams) {
	var request SearchNotesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SearchNotes(ctx, request.(SearchNotesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchNotes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SearchNotesResponseObject); ok {
		if err := validResponse.VisitSearchNotesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FldU+M2FP0rGrWPJgkL7YPfdul+0GGBAtuXHSajWDe2FlkykhygTP57Rx+OHdshCWWB7ewTxpKlc4+O",
	"7j1S7nEi80IKEEbj+B7rJIOcuMcDYgiX6QExkEp1Z18RSplhUhB+qmQByjDQOJ4SriHCRePVPSaJYTOw",
	"T+auABzjiZQciMDzCFOmC07uxlJRULbLVKqcGBxjJszeGxxV3zBhIAVlv+FkArwxnDaKidS2aF6mtuFX",
	"BVMc41+GdUTDEM6wCuLc9p3PI6zgumQKKI6/+gGqGaIKeRvm5QKVnHyDxNipA0WnnCTwQ/PjInh6cmrO",
	"+4AdKCAGjqWBM7guQZstKZxI6lSZk9sjEKnJcLw/Go0inDNRvdiNuvMmAdh4e+VEuLBMLb4knJ9Mcfx1",
	"Y3YvIyxKzsmEA46NKqEHn2GGQyuw3Tfr4mqtmx8k8iS1Y+5brvdKSXUgqZsZRJnbUazAlCB8DLYVR5iJ",
	"GeGMjr9pKRr/Cmmg8a8GopIMR1hIM57KUlDs0YE2YyPlmBOVQgNGCCLCtzt26p0ZUYLkdpm/1sAOAxgc",
	"Nd+5Gf88PznueX3sYbVfn1fwFg3H0nwIMBfvgigvpDzyaCuSzkAXUuhtd3wSuH1IKfUizCM8ZcCp+5QZ",
	"yPW6b/+2oREL5lTJCYfcacnzS5Qidx2NOER9Wjhi2gThM9CPjXcxwMYhtEvO2gDqKVaFYSXw2AisqjcH",
	"78S2DrEfchVYlygei9Zlpq259rVrHewwdh9uF/bjEvfTZubElRM6Jq6OUNCJYoVFhGP8RbBbZFgO2pC8",
	"QEygnHHONCRSUD3A0VKJ/X0fu2TLcpsFR33lltHeAJ6zOnRayoI+FwEteTCbOB+sOEvULK3VEu4+gdX8",
	"9AVdZ70PNl02i9c2gK43LEat6S7CFK3X7/yMrbdLgu201mF2mv5ytaeb3x9Xfyp6FgsYYVuSdSaVCc9c",
	"uvhLcSXkjdiamoCvKqJhkt72CynPw8Sr2o88mN7mLxXCqlxuXiS9XNpK9oNEq0qj7c7EVHY32KeLi1Nk",
	"bQhKpDCKJAZNpUImA6Qp1ejt6aHdZZwlEFK7Jc7uzOOjw4P3x+fv/7CMK45jnBlT6Hg41AW9HUiVDsNX",
	"elh3HmQm5418gKtZcIRnoLRHNRqMBiPbSxYgSMFwjPcGo8GelT8xmdPFMAPCTfaPfU7B5Q4rG0fSIcUx",
	"/gjmk+viTJyvTe7LN6P9LhEXGVgYqFAyAa0R00iVQjCRDiyQ/dHIi1EYEN7xFwVniZtu6Gzl4hi6kVta",
	"VEu3OF0swXYiKkEjIQ3KiUkytzAWZrVaAycFXeY5sWddfJBBcrUIIqviNyR1Yj+pGNL40n44VEDo3YMc",
	"ngGhTIDWW9GYEIE0qBkgo8h0ypIfkEXbQzWiX0nibHe47Bp7uVx2p102n46aFT64h6Mqt6PE2yqk5I1+",
	"7UsV4d+eG5xHUHLqkHGmDapXvK2eo0bzgtmGfoKFrcWzMOwrdeOOAy77KZKDAaWdP1sGelL4kor8bUcN",
	"wZoFVGqgyEgkiFLyBilIQBjkph64MzCO8XUJyjqAkOPb1mMzQluXVpffWejLJ6We9TtbivSntNdLu6Kq",
	"q+qmahqK9vK0bqaQukfC9ZVZfaHyLpymniTS7p3cfNki2VPJvKPE3ScD4E/R/QxbttAN0SgcH15WhM7s",
	"SeVRhemt2wmXYB7c7t7LgLNnHgvGSIncZdtr2BN+2dx2taR1zIJvJijcJrY3RTPJD+/tnzGj84csV9go",
	"rWTvMrS1v3WCDoPhttKbqbp93/o98/G6XfD60+++N7XPB26RHCwwd+f8GiSfglmp949g1oq9vtRbaWn8",
	"peH3tsGtq8me4F2Pn/53a5Pgl7jXJRRNSh8yvv4HlzX+1//ssZEDPiM31ucq5AdGBm7NAH1mWjORRmjC",
	"ibiKbPGTM1BcihTNCC9BIwWmVAIt/xC0yhZf44fya/SfbHkArkCX3PzPjflnK3Am0pe05oFvx2/bBb3w",
	"LgvQes34eaOtLwvbzqBm/bvkrdehnU0qljKxuMEburv8MFpnc5XCsBzCpRICQQvJhBdp0GXjZqS7D96R",
	"5AoE3ZE3Ami9C4igywmjOWCVMbqjXcCt2Zky5Q8lMs9B+AvS+kgbxvCkzC/n/wYAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
