// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for ErrorCode.
const (
	ErrorCodeInternal        ErrorCode = "internal_error"
	ErrorCodeInvalidAuth     ErrorCode = "invalid_auth"
	ErrorCodeInvalidJSON     ErrorCode = "invalid_json"
	ErrorCodeInvalidNote     ErrorCode = "invalid_note"
	ErrorCodeInvalidSearch   ErrorCode = "invalid_search"
	ErrorCodeNotFound        ErrorCode = "not_found"
	ErrorCodeRateLimited     ErrorCode = "rate_limited"
	ErrorCodeRequestTooLarge ErrorCode = "request_too_large"
	ErrorCodeUnauthenticated ErrorCode = "unauthenticated"
	ErrorCodeUsernameTaken   ErrorCode = "username_taken"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ErrorCodeInternal:
		return true
	case ErrorCodeInvalidAuth:
		return true
	case ErrorCodeInvalidJSON:
		return true
	case ErrorCodeInvalidNote:
		return true
	case ErrorCodeInvalidSearch:
		return true
	case ErrorCodeNotFound:
		return true
	case ErrorCodeRateLimited:
		return true
	case ErrorCodeRequestTooLarge:
		return true
	case ErrorCodeUnauthenticated:
		return true
	case ErrorCodeUsernameTaken:
		return true
	default:
		return false
	}
}

// Defines values for ValidationField.
const (
	ValidationFieldBody         ValidationField = "body"
	ValidationFieldCategorySlug ValidationField = "category_slug"
	ValidationFieldCursor       ValidationField = "cursor"
	ValidationFieldDisplayName  ValidationField = "display_name"
	ValidationFieldLimit        ValidationField = "limit"
	ValidationFieldPassword     ValidationField = "password"
	ValidationFieldPlaceSlug    ValidationField = "place_slug"
	ValidationFieldQ            ValidationField = "q"
	ValidationFieldTitle        ValidationField = "title"
	ValidationFieldUsername     ValidationField = "username"
)

// Valid indicates whether the value is a known member of the ValidationField enum.
func (e ValidationField) Valid() bool {
	switch e {
	case ValidationFieldBody:
		return true
	case ValidationFieldCategorySlug:
		return true
	case ValidationFieldCursor:
		return true
	case ValidationFieldDisplayName:
		return true
	case ValidationFieldLimit:
		return true
	case ValidationFieldPassword:
		return true
	case ValidationFieldPlaceSlug:
		return true
	case ValidationFieldQ:
		return true
	case ValidationFieldTitle:
		return true
	case ValidationFieldUsername:
		return true
	default:
		return false
	}
}

// Defines values for ValidationProblemCode.
const (
	ValidationProblemCodeInvalid  ValidationProblemCode = "invalid"
	ValidationProblemCodeRequired ValidationProblemCode = "required"
	ValidationProblemCodeTaken    ValidationProblemCode = "taken"
	ValidationProblemCodeTooLong  ValidationProblemCode = "too_long"
	ValidationProblemCodeTooShort ValidationProblemCode = "too_short"
	ValidationProblemCodeUnknown  ValidationProblemCode = "unknown"
)

// Valid indicates whether the value is a known member of the ValidationProblemCode enum.
func (e ValidationProblemCode) Valid() bool {
	switch e {
	case ValidationProblemCodeInvalid:
		return true
	case ValidationProblemCodeRequired:
		return true
	case ValidationProblemCodeTaken:
		return true
	case ValidationProblemCodeTooLong:
		return true
	case ValidationProblemCodeTooShort:
		return true
	case ValidationProblemCodeUnknown:
		return true
	default:
		return false
	}
}

// AuthSessionResponse defines model for AuthSessionResponse.
type AuthSessionResponse struct {
	// ExpiresAt Unix timestamp in milliseconds.
	ExpiresAt int64       `json:"expires_at"`
	Token     string      `json:"token"`
	User      CurrentUser `json:"user"`
}

// AuthorNotesPage defines model for AuthorNotesPage.
type AuthorNotesPage struct {
	NextCursor *string `json:"next_cursor"`
	Notes      []Note  `json:"notes"`
}

// AuthorSummary defines model for AuthorSummary.
type AuthorSummary struct {
	DisplayName string `json:"display_name"`
	Id          string `json:"id"`
}

// CatalogCategory defines model for CatalogCategory.
type CatalogCategory struct {
	Active       bool         `json:"active"`
	DisplayOrder int32        `json:"display_order"`
	Label        string       `json:"label"`
	Slug         CategorySlug `json:"slug"`
}

// CatalogPlace defines model for CatalogPlace.
type CatalogPlace struct {
	Active       bool      `json:"active"`
	DisplayOrder int32     `json:"display_order"`
	Label        string    `json:"label"`
	Slug         PlaceSlug `json:"slug"`
}

// CategorySlug defines model for CategorySlug.
type CategorySlug = string

// CreateNoteRequest defines model for CreateNoteRequest.
type CreateNoteRequest struct {
	Body         string       `json:"body"`
	CategorySlug CategorySlug `json:"category_slug"`
	PlaceSlug    *PlaceSlug   `json:"place_slug,omitempty"`
	Title        string       `json:"title"`
}

// CreateSessionRequest defines model for CreateSessionRequest.
type CreateSessionRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	DisplayName string `json:"display_name"`
	Password    string `json:"password"`
	Username    string `json:"username"`
}

// CurrentSessionResponse defines model for CurrentSessionResponse.
type CurrentSessionResponse struct {
	// ExpiresAt Unix timestamp in milliseconds.
	ExpiresAt int64       `json:"expires_at"`
	User      CurrentUser `json:"user"`
}

// CurrentUser defines model for CurrentUser.
type CurrentUser struct {
	Author   AuthorSummary `json:"author"`
	Id       string        `json:"id"`
	Username string        `json:"username"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code   ErrorCode            `json:"code"`
	Fields *[]ValidationProblem `json:"fields,omitempty"`
}

// ListCategoriesResponse defines model for ListCategoriesResponse.
type ListCategoriesResponse struct {
	Categories []CatalogCategory `json:"categories"`
}

// ListNotesResponse defines model for ListNotesResponse.
type ListNotesResponse struct {
	Notes []Note `json:"notes"`
}

// ListPlacesResponse defines model for ListPlacesResponse.
type ListPlacesResponse struct {
	Places []CatalogPlace `json:"places"`
}

// Note defines model for Note.
type Note struct {
	Author       AuthorSummary `json:"author"`
	Body         string        `json:"body"`
	CategorySlug CategorySlug  `json:"category_slug"`

	// CreatedAt Unix timestamp in milliseconds.
	CreatedAt int64      `json:"created_at"`
	Id        string     `json:"id"`
	PlaceSlug *PlaceSlug `json:"place_slug"`
	Title     string     `json:"title"`

	// UpdatedAt Unix timestamp in milliseconds.
	UpdatedAt int64 `json:"updated_at"`
}

// PlaceSlug defines model for PlaceSlug.
type PlaceSlug = string

// PublicAuthor defines model for PublicAuthor.
type PublicAuthor struct {
	DisplayName string `json:"display_name"`
	Id          string `json:"id"`
	NoteCount   int64  `json:"note_count"`
}

// ValidationField defines model for ValidationField.
type ValidationField string

// ValidationProblem defines model for ValidationProblem.
type ValidationProblem struct {
	Code  ValidationProblemCode `json:"code"`
	Field ValidationField       `json:"field"`
}

// ValidationProblemCode defines model for ValidationProblem.Code.
type ValidationProblemCode string

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// ListAuthorNotesParams defines parameters for ListAuthorNotes.
type ListAuthorNotesParams struct {
	// Limit Optional page size. Defaults to 20 and must be between 1 and 50.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor returned by the preceding author-notes page.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListNotesParams defines parameters for ListNotes.
type ListNotesParams struct {
	// CategorySlug Optional active category slug used to narrow recent notes.
	CategorySlug *CategorySlug `form:"category_slug,omitempty" json:"category_slug,omitempty"`
}

// SearchNotesParams defines parameters for SearchNotes.
type SearchNotesParams struct {
	// Q Raw user search text. Missing, blank, or overlong values return invalid_search.
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// CategorySlug Optional active category slug used to narrow search results.
	CategorySlug *CategorySlug `form:"category_slug,omitempty" json:"category_slug,omitempty"`
}

// CreateAuthSessionJSONRequestBody defines body for CreateAuthSession for application/json ContentType.
type CreateAuthSessionJSONRequestBody = CreateSessionRequest

// CreateAuthUserJSONRequestBody defines body for CreateAuthUser for application/json ContentType.
type CreateAuthUserJSONRequestBody = CreateUserRequest

// CreateNoteJSONRequestBody defines body for CreateNote for application/json ContentType.
type CreateNoteJSONRequestBody = CreateNoteRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Check process health
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Check API readiness
	// (GET /readyz)
	GetReadiness(w http.ResponseWriter, r *http.Request)
	// Delete the current authenticated session
	// (DELETE /v1/auth/session)
	DeleteAuthSession(w http.ResponseWriter, r *http.Request)
	// Get the current authenticated session
	// (GET /v1/auth/session)
	GetAuthSession(w http.ResponseWriter, r *http.Request)
	// Create an authenticated session
	// (POST /v1/auth/sessions)
	CreateAuthSession(w http.ResponseWriter, r *http.Request)
	// Create a user account
	// (POST /v1/auth/users)
	CreateAuthUser(w http.ResponseWriter, r *http.Request)
	// Get a public author profile
	// (GET /v1/authors/{author_id})
	GetAuthor(w http.ResponseWriter, r *http.Request, authorId string)
	// List an author's notes
	// (GET /v1/authors/{author_id}/notes)
	ListAuthorNotes(w http.ResponseWriter, r *http.Request, authorId string, params ListAuthorNotesParams)
	// List category catalog
	// (GET /v1/categories)
	ListCategories(w http.ResponseWriter, r *http.Request)
	// List recent notes
	// (GET /v1/notes)
	ListNotes(w http.ResponseWriter, r *http.Request, params ListNotesParams)
	// Create a note
	// (POST /v1/notes)
	CreateNote(w http.ResponseWriter, r *http.Request)
	// Get a note
	// (GET /v1/notes/{note_id})
	GetNote(w http.ResponseWriter, r *http.Request, noteId string)
	// List place catalog
	// (GET /v1/places)
	ListPlaces(w http.ResponseWriter, r *http.Request)
	// Search notes
	// (GET /v1/search/notes)
	SearchNotes(w http.ResponseWriter, r *http.Request, params SearchNotesParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Check process health
// (GET /healthz)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Check API readiness
// (GET /readyz)
func (_ Unimplemented) GetReadiness(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete the current authenticated session
// (DELETE /v1/auth/session)
func (_ Unimplemented) DeleteAuthSession(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get the current authenticated session
// (GET /v1/auth/session)
func (_ Unimplemented) GetAuthSession(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create an authenticated session
// (POST /v1/auth/sessions)
func (_ Unimplemented) CreateAuthSession(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a user account
// (POST /v1/auth/users)
func (_ Unimplemented) CreateAuthUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a public author profile
// (GET /v1/authors/{author_id})
func (_ Unimplemented) GetAuthor(w http.ResponseWriter, r *http.Request, authorId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List an author's notes
// (GET /v1/authors/{author_id}/notes)
func (_ Unimplemented) ListAuthorNotes(w http.ResponseWriter, r *http.Request, authorId string, params ListAuthorNotesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List category catalog
// (GET /v1/categories)
func (_ Unimplemented) ListCategories(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List recent notes
// (GET /v1/notes)
func (_ Unimplemented) ListNotes(w http.ResponseWriter, r *http.Request, params ListNotesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a note
// (POST /v1/notes)
func (_ Unimplemented) CreateNote(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a note
// (GET /v1/notes/{note_id})
func (_ Unimplemented) GetNote(w http.ResponseWriter, r *http.Request, noteId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List place catalog
// (GET /v1/places)
func (_ Unimplemented) ListPlaces(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Search notes
// (GET /v1/search/notes)
func (_ Unimplemented) SearchNotes(w http.ResponseWriter, r *http.Request, params SearchNotesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadiness operation middleware
func (siw *ServerInterfaceWrapper) GetReadiness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadiness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAuthSession operation middleware
func (siw *ServerInterfaceWrapper) DeleteAuthSession(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAuthSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthSession operation middleware
func (siw *ServerInterfaceWrapper) GetAuthSession(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAuthSession operation middleware
func (siw *ServerInterfaceWrapper) CreateAuthSession(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAuthSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAuthUser operation middleware
func (siw *ServerInterfaceWrapper) CreateAuthUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAuthUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthor operation middleware
func (siw *ServerInterfaceWrapper) GetAuthor(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "author_id" -------------
	var authorId string

	err = runtime.BindStyledParameterWithOptions("simple", "author_id", chi.URLParam(r, "author_id"), &authorId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "author_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthor(w, r, authorId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAuthorNotes operation middleware
func (siw *ServerInterfaceWrapper) ListAuthorNotes(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "author_id" -------------
	var authorId string

	err = runtime.BindStyledParameterWithOptions("simple", "author_id", chi.URLParam(r, "author_id"), &authorId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "author_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAuthorNotesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAuthorNotes(w, r, authorId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCategories operation middleware
func (siw *ServerInterfaceWrapper) ListCategories(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCategories(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListNotes operation middleware
func (siw *ServerInterfaceWrapper) ListNotes(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListNotesParams

	// ------------- Optional query parameter "category_slug" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "category_slug", r.URL.Query(), &params.CategorySlug, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "category_slug"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "category_slug", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListNotes(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateNote operation middleware
func (siw *ServerInterfaceWrapper) CreateNote(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateNote(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetNote operation middleware
func (siw *ServerInterfaceWrapper) GetNote(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "note_id" -------------
	var noteId string

	err = runtime.BindStyledParameterWithOptions("simple", "note_id", chi.URLParam(r, "note_id"), &noteId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "note_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetNote(w, r, noteId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPlaces operation middleware
func (siw *ServerInterfaceWrapper) ListPlaces(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPlaces(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchNotes operation middleware
func (siw *ServerInterfaceWrapper) SearchNotes(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchNotesParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "category_slug" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "category_slug", r.URL.Query(), &params.CategorySlug, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "category_slug"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "category_slug", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchNotes(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/readyz", wrapper.GetReadiness)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/v1/auth/session", wrapper.DeleteAuthSession)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/auth/session", wrapper.GetAuthSession)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/auth/sessions", wrapper.CreateAuthSession)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/auth/users", wrapper.CreateAuthUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/authors/{author_id}", wrapper.GetAuthor)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/authors/{author_id}/notes", wrapper.ListAuthorNotes)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/categories", wrapper.ListCategories)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/notes", wrapper.ListNotes)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/notes", wrapper.CreateNote)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/notes/{note_id}", wrapper.GetNote)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/places", wrapper.ListPlaces)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/search/notes", wrapper.SearchNotes)
	})

	return r
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth204Response struct {
}

func (response GetHealth204Response) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type GetHealth400JSONResponse ErrorResponse

func (response GetHealth400JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadinessRequestObject struct {
}

type GetReadinessResponseObject interface {
	VisitGetReadinessResponse(w http.ResponseWriter) error
}

type GetReadiness204Response struct {
}

func (response GetReadiness204Response) VisitGetReadinessResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type GetReadiness400JSONResponse ErrorResponse

func (response GetReadiness400JSONResponse) VisitGetReadinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteAuthSessionRequestObject struct {
}

type DeleteAuthSessionResponseObject interface {
	VisitDeleteAuthSessionResponse(w http.ResponseWriter) error
}

type DeleteAuthSession204Response struct {
}

func (response DeleteAuthSession204Response) VisitDeleteAuthSessionResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteAuthSession400JSONResponse ErrorResponse

func (response DeleteAuthSession400JSONResponse) VisitDeleteAuthSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteAuthSession401JSONResponse ErrorResponse

func (response DeleteAuthSession401JSONResponse) VisitDeleteAuthSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteAuthSession500JSONResponse ErrorResponse

func (response DeleteAuthSession500JSONResponse) VisitDeleteAuthSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetAuthSessionRequestObject struct {
}

type GetAuthSessionResponseObject interface {
	VisitGetAuthSessionResponse(w http.ResponseWriter) error
}

type GetAuthSession200JSONResponse CurrentSessionResponse

func (response GetAuthSession200JSONResponse) VisitGetAuthSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAuthSession400JSONResponse ErrorResponse

func (response GetAuthSession400JSONResponse) VisitGetAuthSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetAuthSession401JSONResponse ErrorResponse

func (response GetAuthSession401JSONResponse) VisitGetAuthSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetAuthSession500JSONResponse ErrorResponse

func (response GetAuthSession500JSONResponse) VisitGetAuthSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAuthSessionRequestObject struct {
	Body *CreateAuthSessionJSONRequestBody
}

type CreateAuthSessionResponseObject interface {
	VisitCreateAuthSessionResponse(w http.ResponseWriter) error
}

type CreateAuthSession201JSONResponse AuthSessionResponse

func (response CreateAuthSession201JSONResponse) VisitCreateAuthSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAuthSession400JSONResponse ErrorResponse

func (response CreateAuthSession400JSONResponse) VisitCreateAuthSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAuthSession401JSONResponse ErrorResponse

func (response CreateAuthSession401JSONResponse) VisitCreateAuthSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAuthSession413JSONResponse ErrorResponse

func (response CreateAuthSession413JSONResponse) VisitCreateAuthSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAuthSession429JSONResponse ErrorResponse

func (response CreateAuthSession429JSONResponse) VisitCreateAuthSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAuthSession500JSONResponse ErrorResponse

func (response CreateAuthSession500JSONResponse) VisitCreateAuthSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAuthUserRequestObject struct {
	Body *CreateAuthUserJSONRequestBody
}

type CreateAuthUserResponseObject interface {
	VisitCreateAuthUserResponse(w http.ResponseWriter) error
}

type CreateAuthUser201JSONResponse AuthSessionResponse

func (response CreateAuthUser201JSONResponse) VisitCreateAuthUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAuthUser400JSONResponse ErrorResponse

func (response CreateAuthUser400JSONResponse) VisitCreateAuthUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAuthUser409JSONResponse ErrorResponse

func (response CreateAuthUser409JSONResponse) VisitCreateAuthUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAuthUser413JSONResponse ErrorResponse

func (response CreateAuthUser413JSONResponse) VisitCreateAuthUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAuthUser429JSONResponse ErrorResponse

func (response CreateAuthUser429JSONResponse) VisitCreateAuthUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAuthUser500JSONResponse ErrorResponse

func (response CreateAuthUser500JSONResponse) VisitCreateAuthUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetAuthorRequestObject struct {
	AuthorId string `json:"author_id"`
}

type GetAuthorResponseObject interface {
	VisitGetAuthorResponse(w http.ResponseWriter) error
}

type GetAuthor200JSONResponse PublicAuthor

func (response GetAuthor200JSONResponse) VisitGetAuthorResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAuthor400JSONResponse ErrorResponse

func (response GetAuthor400JSONResponse) VisitGetAuthorResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetAuthor404JSONResponse ErrorResponse

func (response GetAuthor404JSONResponse) VisitGetAuthorResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetAuthor500JSONResponse ErrorResponse

func (response GetAuthor500JSONResponse) VisitGetAuthorResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListAuthorNotesRequestObject struct {
	AuthorId string `json:"author_id"`
	Params   ListAuthorNotesParams
}

type ListAuthorNotesResponseObject interface {
	VisitListAuthorNotesResponse(w http.ResponseWriter) error
}

type ListAuthorNotes200JSONResponse AuthorNotesPage

func (response ListAuthorNotes200JSONResponse) VisitListAuthorNotesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListAuthorNotes400JSONResponse ErrorResponse

func (response ListAuthorNotes400JSONResponse) VisitListAuthorNotesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListAuthorNotes404JSONResponse ErrorResponse

func (response ListAuthorNotes404JSONResponse) VisitListAuthorNotesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListAuthorNotes500JSONResponse ErrorResponse

func (response ListAuthorNotes500JSONResponse) VisitListAuthorNotesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListCategoriesRequestObject struct {
}

type ListCategoriesResponseObject interface {
	VisitListCategoriesResponse(w http.ResponseWriter) error
}

type ListCategories200JSONResponse ListCategoriesResponse

func (response ListCategories200JSONResponse) VisitListCategoriesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListCategories400JSONResponse ErrorResponse

func (response ListCategories400JSONResponse) VisitListCategoriesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListCategories500JSONResponse ErrorResponse

func (response ListCategories500JSONResponse) VisitListCategoriesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListNotesRequestObject struct {
	Params ListNotesParams
}

type ListNotesResponseObject interface {
	VisitListNotesResponse(w http.ResponseWriter) error
}

type ListNotes200JSONResponse ListNotesResponse

func (response ListNotes200JSONResponse) VisitListNotesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListNotes400JSONResponse ErrorResponse

func (response ListNotes400JSONResponse) VisitListNotesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListNotes500JSONResponse ErrorResponse

func (response ListNotes500JSONResponse) VisitListNotesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateNoteRequestObject struct {
	Body *CreateNoteJSONRequestBody
}

type CreateNoteResponseObject interface {
	VisitCreateNoteResponse(w http.ResponseWriter) error
}

type CreateNote201JSONResponse Note

func (response CreateNote201JSONResponse) VisitCreateNoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateNote400JSONResponse ErrorResponse

func (response CreateNote400JSONResponse) VisitCreateNoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateNote401JSONResponse ErrorResponse

func (response CreateNote401JSONResponse) VisitCreateNoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateNote413JSONResponse ErrorResponse

func (response CreateNote413JSONResponse) VisitCreateNoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type CreateNote500JSONResponse ErrorResponse

func (response CreateNote500JSONResponse) VisitCreateNoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetNoteRequestObject struct {
	NoteId string `json:"note_id"`
}

type GetNoteResponseObject interface {
	VisitGetNoteResponse(w http.ResponseWriter) error
}

type GetNote200JSONResponse Note

func (response GetNote200JSONResponse) VisitGetNoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetNote400JSONResponse ErrorResponse

func (response GetNote400JSONResponse) VisitGetNoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetNote404JSONResponse ErrorResponse

func (response GetNote404JSONResponse) VisitGetNoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetNote500JSONResponse ErrorResponse

func (response GetNote500JSONResponse) VisitGetNoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListPlacesRequestObject struct {
}

type ListPlacesResponseObject interface {
	VisitListPlacesResponse(w http.ResponseWriter) error
}

type ListPlaces200JSONResponse ListPlacesResponse

func (response ListPlaces200JSONResponse) VisitListPlacesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListPlaces400JSONResponse ErrorResponse

func (response ListPlaces400JSONResponse) VisitListPlacesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListPlaces500JSONResponse ErrorResponse

func (response ListPlaces500JSONResponse) VisitListPlacesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type SearchNotesRequestObject struct {
	Params SearchNotesParams
}

type SearchNotesResponseObject interface {
	VisitSearchNotesResponse(w http.ResponseWriter) error
}

type SearchNotes200JSONResponse ListNotesResponse

func (response SearchNotes200JSONResponse) VisitSearchNotesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SearchNotes400JSONResponse ErrorResponse

func (response SearchNotes400JSONResponse) VisitSearchNotesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type SearchNotes500JSONResponse ErrorResponse

func (response SearchNotes500JSONResponse) VisitSearchNotesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Check process health
	// (GET /healthz)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// Check API readiness
	// (GET /readyz)
	GetReadiness(ctx context.Context, request GetReadinessRequestObject) (GetReadinessResponseObject, error)
	// Delete the current authenticated session
	// (DELETE /v1/auth/session)
	DeleteAuthSession(ctx context.Context, request DeleteAuthSessionRequestObject) (DeleteAuthSessionResponseObject, error)
	// Get the current authenticated session
	// (GET /v1/auth/session)
	GetAuthSession(ctx context.Context, request GetAuthSessionRequestObject) (GetAuthSessionResponseObject, error)
	// Create an authenticated session
	// (POST /v1/auth/sessions)
	CreateAuthSession(ctx context.Context, request CreateAuthSessionRequestObject) (CreateAuthSessionResponseObject, error)
	// Create a user account
	// (POST /v1/auth/users)
	CreateAuthUser(ctx context.Context, request CreateAuthUserRequestObject) (CreateAuthUserResponseObject, error)
	// Get a public author profile
	// (GET /v1/authors/{author_id})
	GetAuthor(ctx context.Context, request GetAuthorRequestObject) (GetAuthorResponseObject, error)
	// List an author's notes
	// (GET /v1/authors/{author_id}/notes)
	ListAuthorNotes(ctx context.Context, request ListAuthorNotesRequestObject) (ListAuthorNotesResponseObject, error)
	// List category catalog
	// (GET /v1/categories)
	ListCategories(ctx context.Context, request ListCategoriesRequestObject) (ListCategoriesResponseObject, error)
	// List recent notes
	// (GET /v1/notes)
	ListNotes(ctx context.Context, request ListNotesRequestObject) (ListNotesResponseObject, error)
	// Create a note
	// (POST /v1/notes)
	CreateNote(ctx context.Context, request CreateNoteRequestObject) (CreateNoteResponseObject, error)
	// Get a note
	// (GET /v1/notes/{note_id})
	GetNote(ctx context.Context, request GetNoteRequestObject) (GetNoteResponseObject, error)
	// List place catalog
	// (GET /v1/places)
	ListPlaces(ctx context.Context, request ListPlacesRequestObject) (ListPlacesResponseObject, error)
	// Search notes
	// (GET /v1/search/notes)
	SearchNotes(ctx context.Context, request SearchNotesRequestObject) (SearchNotesResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReadiness operation middleware
func (sh *strictHandler) GetReadiness(w http.ResponseWriter, r *http.Request) {
	var request GetReadinessRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetReadiness(ctx, request.(GetReadinessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReadiness")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetReadinessResponseObject); ok {
		if err := validResponse.VisitGetReadinessResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteAuthSession operation middleware
func (sh *strictHandler) DeleteAuthSession(w http.ResponseWriter, r *http.Request) {
	var request DeleteAuthSessionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteAuthSession(ctx, request.(DeleteAuthSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteAuthSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteAuthSessionResponseObject); ok {
		if err := validResponse.VisitDeleteAuthSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAuthSession operation middleware
func (sh *strictHandler) GetAuthSession(w http.ResponseWriter, r *http.Request) {
	var request GetAuthSessionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAuthSession(ctx, request.(GetAuthSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAuthSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAuthSessionResponseObject); ok {
		if err := validResponse.VisitGetAuthSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateAuthSession operation middleware
func (sh *strictHandler) CreateAuthSession(w http.ResponseWriter, r *http.Request) {
	var request CreateAuthSessionRequestObject

	var body CreateAuthSessionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAuthSession(ctx, request.(CreateAuthSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAuthSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateAuthSessionResponseObject); ok {
		if err := validResponse.VisitCreateAuthSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateAuthUser operation middleware
func (sh *strictHandler) CreateAuthUser(w http.ResponseWriter, r *http.Request) {
	var request CreateAuthUserRequestObject

	var body CreateAuthUserJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAuthUser(ctx, request.(CreateAuthUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAuthUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateAuthUserResponseObject); ok {
		if err := validResponse.VisitCreateAuthUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAuthor operation middleware
func (sh *strictHandler) GetAuthor(w http.ResponseWriter, r *http.Request, authorId string) {
	var request GetAuthorRequestObject

	request.AuthorId = authorId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAuthor(ctx, request.(GetAuthorRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAuthor")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAuthorResponseObject); ok {
		if err := validResponse.VisitGetAuthorResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListAuthorNotes operation middleware
func (sh *strictHandler) ListAuthorNotes(w http.ResponseWriter, r *http.Request, authorId string, params ListAuthorNotesParams) {
	var request ListAuthorNotesRequestObject

	request.AuthorId = authorId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAuthorNotes(ctx, request.(ListAuthorNotesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAuthorNotes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAuthorNotesResponseObject); ok {
		if err := validResponse.VisitListAuthorNotesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListCategories operation middleware
func (sh *strictHandler) ListCategories(w http.ResponseWriter, r *http.Request) {
	var request ListCategoriesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListCategories(ctx, request.(ListCategoriesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListCategories")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListCategoriesResponseObject); ok {
		if err := validResponse.VisitListCategoriesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListNotes operation middleware
func (sh *strictHandler) ListNotes(w http.ResponseWriter, r *http.Request, params ListNotesParams) {
	var request ListNotesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListNotes(ctx, request.(ListNotesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListNotes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListNotesResponseObject); ok {
		if err := validResponse.VisitListNotesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateNote operation middleware
func (sh *strictHandler) CreateNote(w http.ResponseWriter, r *http.Request) {
	var request CreateNoteRequestObject

	var body CreateNoteJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateNote(ctx, request.(CreateNoteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateNote")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateNoteResponseObject); ok {
		if err := validResponse.VisitCreateNoteResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetNote operation middleware
func (sh *strictHandler) GetNote(w http.ResponseWriter, r *http.Request, noteId string) {
	var request GetNoteRequestObject

	request.NoteId = noteId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetNote(ctx, request.(GetNoteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetNote")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetNoteResponseObject); ok {
		if err := validResponse.VisitGetNoteResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListPlaces operation middleware
func (sh *strictHandler) ListPlaces(w http.ResponseWriter, r *http.Request) {
	var request ListPlacesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListPlaces(ctx, request.(ListPlacesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListPlaces")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListPlacesResponseObject); ok {
		if err := validResponse.VisitListPlacesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SearchNotes operation middleware
func (sh *strictHandler) SearchNotes(w http.ResponseWriter, r *http.Request, params SearchNotesParams) {
	var request SearchNotesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SearchNotes(ctx, request.(SearchNotesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchNotes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SearchNotesResponseObject); ok {
		if err := validResponse.VisitSearchNotesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FtZb+M4Ev4rBHeBfVHbTrp7gfFbOt0z04tMOptjXxqBwUhlmROKVEgqxwT+7wseOk35yMaJs8ibTcql",
	"rz7WxSL9iGOR5YID1wqPH7GKZ5AR+/Gg0LMzUIoKfgoqF1yBGSZJQjUVnLATKXKQmoLC4ylhCiKcN4Ye",
	"MdznVIKaEG2+JaBiSXPzWzzGF5zeI00zUJpkOaIcZZQxqiAWPFEDHOGpkJn5JaZc//MTjnBGOc2KDI9H",
	"EdYPObgpSEHieYS1uAZu3uOnlJaUp2amUCDNxN8lTPEY/21Yqzz0+g4PCymB6wvz6HweYQk3BZWQ4PFP",
	"LzlqquOFXlZAxNWfEGvzNkObkMdCgzoh6aaUcbjXk7iQSljIGbk/Ap7qGR5/3tu3FJTf9yLMC8bIFQM8",
	"1rKAaFFzblAYOVRDplZxYDBbJp0YIiV5WCDDiYxaQPtpOCuyjMiHDUlIqMoZeZhwkkFwRWkSGO4ApQmO",
	"2pJCMA+JJkykh0RDKjYGSmJNb5sQr4RgQLiRXL5ayMSZX9OeP+7jkA0zcgUsqLFiRbrShr0SZ+bZLh1W",
	"QPmGqETehbmEohNGYnjT/FgNnp+cmvMQsEMJRINxrVO4KUDpDSm8EslDJxJ8Go1G3VCw8N7YA5tsbjkR",
	"zg1T1S8JYz+mePxzbXYv1whNmmoGHcX29lfp1Y3MVkjkSOrqHFwuuxpVVnvKguREqTshk95U0xO1OtCr",
	"J6NaYj9ik5eeBndlLN2iPuvEX5d331Cd8b9WE+tVEU0JG8Zcm3hXIWyn576UuokB2HzbsAKPI6TcNymF",
	"PBSJlQrcUP3TUiw5YRMwszjClN8SRpOJEdT4+qcSvPHV1CONrwqIjM3jXOjJVBTcoJJEw4TRjGqwX50j",
	"TbQQE0Zkan5fcPMa4JqaINJUZaKJKf8uu7EowvcfDPYPt8Q+p4wSlWbfvTY4ao5ZjAdOn+7wv85+HAeG",
	"j51+3eGzUs9q4ljoX72+1dgp0XBU6V0POwLOhTjy6ldTFws81FOekHPHR7mOT/TZ2C//MiOt7WQe4SkF",
	"lqxfzP7HsEQMmBMprhhkKytbiyhkrkdUaZ8hKain6lsJWFuFbm26UoH6FX1q2G3JEzXY2maiD6ytKJ6K",
	"1pYwG3PtitxVsL3sEG6r9osE7LIwfN7KL7blRvJcqXQxffbkmZesOBeTXJ5sU+lQolxaubboqDJpa3Fa",
	"oEOGWJMT0vikuGI0Pqgsb+ubc9eLmMSi4Lq72VtZdK3c2bekh9ios8GvJo00645NVuKmXeL0FboRtsWG",
	"kdZtkCwrHjogzz2wzvAXh7Mz2vLjhdnaGBam/r04dFFr2JVTK9yZ+er0Pw7+7Miz0cXsyWmtT5mtn1ZN",
	"lItamUuETZWnZkJq/5kJy3/Br7m4a1SSZnqDSm8BcVlY+dcG58+FOPNQ+uaPHLzg9EWFOTj9vVIkLLyq",
	"26alD6xXQDmX6XqhExL1lU3zCCuIC0n1w5mR6LsZQCRIWwGXzWbbFrLDdeicaZ3juZFB+VQsBuXfz89P",
	"kCmYUSy4liTWaCok0jNAKkkUOjj5PrBeGIOvHFy0whfHR98Pvx2ffftqTEAy/y41Hg5VntwPhEyH/ldq",
	"WD88mOmMNXIILt+CI3wLUjlUo8FoMDJPiRw4ySke44+D0eCjjRR6ZgkYzoAwPfvLfE7BhkJjx5bn7wke",
	"499A/24fsRsVV/rYX+6PPi0ScT4DAwPlUsSgFKIKyYJzytOBAfJpNHLewTW4uEvynJnSngo+tDupque/",
	"VjFeFWN2cRax+K0VSgQoxIVGGdHxzC6MgVmu1sDZR9kcxocziK8rJWal/pqk1td+lAwpfGl+OJRAkoel",
	"HJ4CSSgHpTaiMSYcKZC3gLQk0ymN3yCL5gnZ0L6XxNu9oakshsr1XhwrDFz92ib0qx1vHAitzaoXju6I",
	"QhJuxTUku86pAbf3OuCog9bagltEn1+aLsdJwRILyK2ci69uQQetCG9L9WZs/3lpSvLaNJ0BWQGx62y1",
	"lSzFNuzVCjLZqs/Fl5rj89HV06Hs4a3Urqbp3dbflq2noFt2+jSD/60jZU1rD8Rl180QKuAE7myg6weW",
	"3i++O/A8LhA6NZm3C0Kz6Z4vuOHz2VboNkKfD0pIDNeEKXQHEhDcxzPCU0hslUh2wzlt+WrgFHqGXHMT",
	"EQnIb0dexzmb1C2A2fv4OkyZnbkJF1oIZPv1Ds7+Ly8IRwiUEf6AmEgpL5GVHKEpo+lMm9WUEAPX7AER",
	"rSHLdySmucZRIH/XtaN7gvCnRKpCgVwrTNnjrG3GqOY56e4GKMOXrYh9Qw8RniBFUw4Jom8iLP3ysuDK",
	"npuJAoTZ3R+yzZr3wFQGJmM+Rf6WI5NZ5L6w5FyGxK7DuywYCamGj+7DhCbzZT2Cg7KvnhNJMtA2iP18",
	"xNRAzYltQfi+USUQd0NK1OCme0B+ucVtSauDH6DazSMHHOVSTCmDt7Ad+fSy4DxBJhobaPbKwC5tQxy+",
	"rl+Y7QVBeWiNO94hpFrqIMPqWDfoJkdU6caN1i06S9RtH/3IXfMf5SQFpOhfMEBfYUoKpk3IRfsjmzez",
	"wkRiQFeg7wA42rOjn0cD29rHY3xTgHyo0ZVHMzWSxAnFY3v9jNy7c6jPo8ah1F7oUGoRMLkp7JZP2Xir",
	"C2ky+tWDXcjcBOCE8tSv1wdLvFWuD6o/PWpiXX4h+CUDUPeec8CqD9zSiWnDkv9h/QzU64ai2ogDxc17",
	"BLJAGFU6vHCtUGQiRLlvqJ9aFoXaV2F6w0595Wab7b2eyz0BhsojVhS7uyJIiju1+xl1F6yoXvGg9cQd",
	"ZhvG4+/l1MazOl31JKqe5OLuetcQFCtSU20mJsVwIqW486Vzaf49sbpzb2DNXWv7yv7llg29ff0rsH6n",
	"LU3fTXu1affHxKbVNCzameflPFraLfHXPrfXKWn+I+GFOyXuamCYYcNWszWyG80Qi8q/3mz4X7VH2zhA",
	"yahStqJEFk+4d7eLPZLd6TqYpd3wbKdqSvi7513Pbmaq4aO9mbaiE+G9ffXWygvbmS7EKld+bzj0R7id",
	"bDc03KHTbFhu7PV16966zF3n3nYt37k0HuqMmSfei/iNKx23xMFSJ29Suqx6d3/PWVHEu/+2rFXGn5I7",
	"1xp2gpGGez1Af7i0GKErRvh1ZDK4uAXJBE9NoixA+e4Mav9tqK+2v8FPa1yts7fwwCWogun/893FH8bA",
	"Tb3yivsLz7flt1vKvbKXeWjBHcVZYy4UhW39Im/DXnLg7NC8TUiaUl5dfh3av054aQvOVXBNM/D3MRHw",
	"JBeUOyP1dtm4VLjoB19IfA08+SDuOCS1FxCetANGU2AZMRalXTROgNyBqb9aGMJlC7dFGcFDkV4BQoa0",
	"Ood7/WFKpdvhiSwD7q5J1/0BL8Mtzvxy/t8AAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
