// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for ErrorCode.
const (
	ErrorCodeIdempotencyConflict       ErrorCode = "idempotency_conflict"
	ErrorCodeInternal                  ErrorCode = "internal_error"
	ErrorCodeInvalidAuth               ErrorCode = "invalid_auth"
	ErrorCodeInvalidJSON               ErrorCode = "invalid_json"
	ErrorCodeInvalidMedia              ErrorCode = "invalid_media"
	ErrorCodeInvalidNote               ErrorCode = "invalid_note"
	ErrorCodeInvalidSearch             ErrorCode = "invalid_search"
	ErrorCodeMediaIntegrityError       ErrorCode = "media_integrity_error"
	ErrorCodeMediaStagingQuotaExceeded ErrorCode = "media_staging_quota_exceeded"
	ErrorCodeMediaStorageUnavailable   ErrorCode = "media_storage_unavailable"
	ErrorCodeNotFound                  ErrorCode = "not_found"
	ErrorCodeRateLimited               ErrorCode = "rate_limited"
	ErrorCodeRequestTooLarge           ErrorCode = "request_too_large"
	ErrorCodeTooManyImages             ErrorCode = "too_many_images"
	ErrorCodeUnauthenticated           ErrorCode = "unauthenticated"
	ErrorCodeUnsupportedMediaType      ErrorCode = "unsupported_media_type"
	ErrorCodeUploadExpired             ErrorCode = "upload_expired"
	ErrorCodeUploadInProgress          ErrorCode = "upload_in_progress"
	ErrorCodeUsernameTaken             ErrorCode = "username_taken"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ErrorCodeIdempotencyConflict:
		return true
	case ErrorCodeInternal:
		return true
	case ErrorCodeInvalidAuth:
		return true
	case ErrorCodeInvalidJSON:
		return true
	case ErrorCodeInvalidMedia:
		return true
	case ErrorCodeInvalidNote:
		return true
	case ErrorCodeInvalidSearch:
		return true
	case ErrorCodeMediaIntegrityError:
		return true
	case ErrorCodeMediaStagingQuotaExceeded:
		return true
	case ErrorCodeMediaStorageUnavailable:
		return true
	case ErrorCodeNotFound:
		return true
	case ErrorCodeRateLimited:
		return true
	case ErrorCodeRequestTooLarge:
		return true
	case ErrorCodeTooManyImages:
		return true
	case ErrorCodeUnauthenticated:
		return true
	case ErrorCodeUnsupportedMediaType:
		return true
	case ErrorCodeUploadExpired:
		return true
	case ErrorCodeUploadInProgress:
		return true
	case ErrorCodeUsernameTaken:
		return true
	default:
		return false
	}
}

// Defines values for ImageUploadReceiptContentType.
const (
	ImageUploadReceiptContentTypeImagejpeg ImageUploadReceiptContentType = "image/jpeg"
	ImageUploadReceiptContentTypeImagepng  ImageUploadReceiptContentType = "image/png"
)

// Valid indicates whether the value is a known member of the ImageUploadReceiptContentType enum.
func (e ImageUploadReceiptContentType) Valid() bool {
	switch e {
	case ImageUploadReceiptContentTypeImagejpeg:
		return true
	case ImageUploadReceiptContentTypeImagepng:
		return true
	default:
		return false
	}
}

// Defines values for NoteImageContentType.
const (
	NoteImageContentTypeImagejpeg NoteImageContentType = "image/jpeg"
	NoteImageContentTypeImagepng  NoteImageContentType = "image/png"
)

// Valid indicates whether the value is a known member of the NoteImageContentType enum.
func (e NoteImageContentType) Valid() bool {
	switch e {
	case NoteImageContentTypeImagejpeg:
		return true
	case NoteImageContentTypeImagepng:
		return true
	default:
		return false
	}
}

// Defines values for ValidationField.
const (
	ValidationFieldBody            ValidationField = "body"
	ValidationFieldCategorySlug    ValidationField = "category_slug"
	ValidationFieldClientRequestID ValidationField = "client_request_id"
	ValidationFieldCursor          ValidationField = "cursor"
	ValidationFieldDisplayName     ValidationField = "display_name"
	ValidationFieldFile            ValidationField = "file"
	ValidationFieldImageUploadIDs  ValidationField = "image_upload_ids"
	ValidationFieldLimit           ValidationField = "limit"
	ValidationFieldPassword        ValidationField = "password"
	ValidationFieldPlaceSlug       ValidationField = "place_slug"
	ValidationFieldQ               ValidationField = "q"
	ValidationFieldTitle           ValidationField = "title"
	ValidationFieldUploadRequestID ValidationField = "upload_request_id"
	ValidationFieldUsername        ValidationField = "username"
)

// Valid indicates whether the value is a known member of the ValidationField enum.
func (e ValidationField) Valid() bool {
	switch e {
	case ValidationFieldBody:
		return true
	case ValidationFieldCategorySlug:
		return true
	case ValidationFieldClientRequestID:
		return true
	case ValidationFieldCursor:
		return true
	case ValidationFieldDisplayName:
		return true
	case ValidationFieldFile:
		return true
	case ValidationFieldImageUploadIDs:
		return true
	case ValidationFieldLimit:
		return true
	case ValidationFieldPassword:
		return true
	case ValidationFieldPlaceSlug:
		return true
	case ValidationFieldQ:
		return true
	case ValidationFieldTitle:
		return true
	case ValidationFieldUploadRequestID:
		return true
	case ValidationFieldUsername:
		return true
	default:
		return false
	}
}

// Defines values for ValidationProblemCode.
const (
	ValidationProblemCodeInvalid  ValidationProblemCode = "invalid"
	ValidationProblemCodeRequired ValidationProblemCode = "required"
	ValidationProblemCodeTaken    ValidationProblemCode = "taken"
	ValidationProblemCodeTooLong  ValidationProblemCode = "too_long"
	ValidationProblemCodeTooShort ValidationProblemCode = "too_short"
	ValidationProblemCodeUnknown  ValidationProblemCode = "unknown"
)

// Valid indicates whether the value is a known member of the ValidationProblemCode enum.
func (e ValidationProblemCode) Valid() bool {
	switch e {
	case ValidationProblemCodeInvalid:
		return true
	case ValidationProblemCodeRequired:
		return true
	case ValidationProblemCodeTaken:
		return true
	case ValidationProblemCodeTooLong:
		return true
	case ValidationProblemCodeTooShort:
		return true
	case ValidationProblemCodeUnknown:
		return true
	default:
		return false
	}
}

// AuthSessionResponse defines model for AuthSessionResponse.
type AuthSessionResponse struct {
	// ExpiresAt Unix timestamp in milliseconds.
	ExpiresAt int64       `json:"expires_at"`
	Token     string      `json:"token"`
	User      CurrentUser `json:"user"`
}

// AuthorNotesPage defines model for AuthorNotesPage.
type AuthorNotesPage struct {
	NextCursor *string `json:"next_cursor"`
	Notes      []Note  `json:"notes"`
}

// AuthorSummary defines model for AuthorSummary.
type AuthorSummary struct {
	DisplayName string `json:"display_name"`
	Id          string `json:"id"`
}

// CatalogCategory defines model for CatalogCategory.
type CatalogCategory struct {
	Active       bool         `json:"active"`
	DisplayOrder int32        `json:"display_order"`
	Label        string       `json:"label"`
	Slug         CategorySlug `json:"slug"`
}

// CatalogPlace defines model for CatalogPlace.
type CatalogPlace struct {
	Active       bool      `json:"active"`
	DisplayOrder int32     `json:"display_order"`
	Label        string    `json:"label"`
	Slug         PlaceSlug `json:"slug"`
}

// CategorySlug defines model for CategorySlug.
type CategorySlug = string

// CreateNoteRequest defines model for CreateNoteRequest.
type CreateNoteRequest struct {
	Body         string       `json:"body"`
	CategorySlug CategorySlug `json:"category_slug"`
	PlaceSlug    *PlaceSlug   `json:"place_slug,omitempty"`
	Title        string       `json:"title"`
}

// CreateSessionRequest defines model for CreateSessionRequest.
type CreateSessionRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	DisplayName string `json:"display_name"`
	Password    string `json:"password"`
	Username    string `json:"username"`
}

// CurrentSessionResponse defines model for CurrentSessionResponse.
type CurrentSessionResponse struct {
	// ExpiresAt Unix timestamp in milliseconds.
	ExpiresAt int64       `json:"expires_at"`
	User      CurrentUser `json:"user"`
}

// CurrentUser defines model for CurrentUser.
type CurrentUser struct {
	Author   AuthorSummary `json:"author"`
	Id       string        `json:"id"`
	Username string        `json:"username"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code   ErrorCode            `json:"code"`
	Fields *[]ValidationProblem `json:"fields,omitempty"`
}

// ImageUploadReceipt defines model for ImageUploadReceipt.
type ImageUploadReceipt struct {
	ByteSize      int64                         `json:"byte_size"`
	ContentType   ImageUploadReceiptContentType `json:"content_type"`
	ExpiresAt     int64                         `json:"expires_at"`
	Height        int32                         `json:"height"`
	ImageUploadId openapi_types.UUID            `json:"image_upload_id"`
	Width         int32                         `json:"width"`
}

// ImageUploadReceiptContentType defines model for ImageUploadReceipt.ContentType.
type ImageUploadReceiptContentType string

// ListCategoriesResponse defines model for ListCategoriesResponse.
type ListCategoriesResponse struct {
	Categories []CatalogCategory `json:"categories"`
}

// ListNotesResponse defines model for ListNotesResponse.
type ListNotesResponse struct {
	Notes []Note `json:"notes"`
}

// ListPlacesResponse defines model for ListPlacesResponse.
type ListPlacesResponse struct {
	Places []CatalogPlace `json:"places"`
}

// Note defines model for Note.
type Note struct {
	Author       AuthorSummary `json:"author"`
	Body         string        `json:"body"`
	CategorySlug CategorySlug  `json:"category_slug"`

	// CreatedAt Unix timestamp in milliseconds.
	CreatedAt int64       `json:"created_at"`
	Id        string      `json:"id"`
	Images    []NoteImage `json:"images"`
	PlaceSlug *PlaceSlug  `json:"place_slug"`
	Title     string      `json:"title"`

	// UpdatedAt Unix timestamp in milliseconds.
	UpdatedAt int64 `json:"updated_at"`
}

// NoteImage defines model for NoteImage.
type NoteImage struct {
	ByteSize    int64                `json:"byte_size"`
	ContentType NoteImageContentType `json:"content_type"`
	CreatedAt   int64                `json:"created_at"`
	Height      int32                `json:"height"`
	Id          string               `json:"id"`
	Position    int32                `json:"position"`
	UpdatedAt   int64                `json:"updated_at"`
	Url         string               `json:"url"`
	Width       int32                `json:"width"`
}

// NoteImageContentType defines model for NoteImage.ContentType.
type NoteImageContentType string

// PlaceSlug defines model for PlaceSlug.
type PlaceSlug = string

// PrepareImageUploadMultipart defines model for PrepareImageUploadMultipart.
type PrepareImageUploadMultipart struct {
	File            openapi_types.File `json:"file"`
	UploadRequestId openapi_types.UUID `json:"upload_request_id"`
}

// PublicAuthor defines model for PublicAuthor.
type PublicAuthor struct {
	DisplayName string `json:"display_name"`
	Id          string `json:"id"`
	NoteCount   int64  `json:"note_count"`
}

// ValidationField defines model for ValidationField.
type ValidationField string

// ValidationProblem defines model for ValidationProblem.
type ValidationProblem struct {
	Code  ValidationProblemCode `json:"code"`
	Field ValidationField       `json:"field"`
}

// ValidationProblemCode defines model for ValidationProblem.Code.
type ValidationProblemCode string

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// ListAuthorNotesParams defines parameters for ListAuthorNotes.
type ListAuthorNotesParams struct {
	// Limit Optional page size. Defaults to 20 and must be between 1 and 50.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor returned by the preceding author-notes page.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListNotesParams defines parameters for ListNotes.
type ListNotesParams struct {
	// CategorySlug Optional active category slug used to narrow recent notes.
	CategorySlug *CategorySlug `form:"category_slug,omitempty" json:"category_slug,omitempty"`
}

// SearchNotesParams defines parameters for SearchNotes.
type SearchNotesParams struct {
	// Q Raw user search text. Missing, blank, or overlong values return invalid_search.
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// CategorySlug Optional active category slug used to narrow search results.
	CategorySlug *CategorySlug `form:"category_slug,omitempty" json:"category_slug,omitempty"`
}

// CreateAuthSessionJSONRequestBody defines body for CreateAuthSession for application/json ContentType.
type CreateAuthSessionJSONRequestBody = CreateSessionRequest

// CreateAuthUserJSONRequestBody defines body for CreateAuthUser for application/json ContentType.
type CreateAuthUserJSONRequestBody = CreateUserRequest

// PrepareImageUploadMultipartRequestBody defines body for PrepareImageUpload for multipart/form-data ContentType.
type PrepareImageUploadMultipartRequestBody = PrepareImageUploadMultipart

// CreateNoteJSONRequestBody defines body for CreateNote for application/json ContentType.
type CreateNoteJSONRequestBody = CreateNoteRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetHealth request
	GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetReadiness request
	GetReadiness(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteAuthSession request
	DeleteAuthSession(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAuthSession request
	GetAuthSession(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateAuthSessionWithBody request with any body
	CreateAuthSessionWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateAuthSession(ctx context.Context, body CreateAuthSessionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateAuthUserWithBody request with any body
	CreateAuthUserWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateAuthUser(ctx context.Context, body CreateAuthUserJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAuthor request
	GetAuthor(ctx context.Context, authorId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListAuthorNotes request
	ListAuthorNotes(ctx context.Context, authorId string, params *ListAuthorNotesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListCategories request
	ListCategories(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PrepareImageUploadWithBody request with any body
	PrepareImageUploadWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListNotes request
	ListNotes(ctx context.Context, params *ListNotesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateNoteWithBody request with any body
	CreateNoteWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateNote(ctx context.Context, body CreateNoteJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetNote request
	GetNote(ctx context.Context, noteId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListPlaces request
	ListPlaces(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SearchNotes request
	SearchNotes(ctx context.Context, params *SearchNotesParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetReadiness(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetReadinessRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteAuthSession(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteAuthSessionRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAuthSession(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAuthSessionRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateAuthSessionWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateAuthSessionRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateAuthSession(ctx context.Context, body CreateAuthSessionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateAuthSessionRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateAuthUserWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateAuthUserRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateAuthUser(ctx context.Context, body CreateAuthUserJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateAuthUserRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAuthor(ctx context.Context, authorId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAuthorRequest(c.Server, authorId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListAuthorNotes(ctx context.Context, authorId string, params *ListAuthorNotesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListAuthorNotesRequest(c.Server, authorId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListCategories(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListCategoriesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PrepareImageUploadWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPrepareImageUploadRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListNotes(ctx context.Context, params *ListNotesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListNotesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateNoteWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateNoteRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateNote(ctx context.Context, body CreateNoteJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateNoteRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetNote(ctx context.Context, noteId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetNoteRequest(c.Server, noteId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListPlaces(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListPlacesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SearchNotes(ctx context.Context, params *SearchNotesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSearchNotesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetHealthRequest generates requests for GetHealth
func NewGetHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/healthz")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetReadinessRequest generates requests for GetReadiness
func NewGetReadinessRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/readyz")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDeleteAuthSessionRequest generates requests for DeleteAuthSession
func NewDeleteAuthSessionRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/auth/session")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetAuthSessionRequest generates requests for GetAuthSession
func NewGetAuthSessionRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/auth/session")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateAuthSessionRequest calls the generic CreateAuthSession builder with application/json body
func NewCreateAuthSessionRequest(server string, body CreateAuthSessionJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateAuthSessionRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateAuthSessionRequestWithBody generates requests for CreateAuthSession with any type of body
func NewCreateAuthSessionRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/auth/sessions")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCreateAuthUserRequest calls the generic CreateAuthUser builder with application/json body
func NewCreateAuthUserRequest(server string, body CreateAuthUserJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateAuthUserRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateAuthUserRequestWithBody generates requests for CreateAuthUser with any type of body
func NewCreateAuthUserRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/auth/users")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetAuthorRequest generates requests for GetAuthor
func NewGetAuthorRequest(server string, authorId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "author_id", authorId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/authors/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListAuthorNotesRequest generates requests for ListAuthorNotes
func NewListAuthorNotesRequest(server string, authorId string, params *ListAuthorNotesParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "author_id", authorId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/authors/%s/notes", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Cursor != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "cursor", *params.Cursor, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListCategoriesRequest generates requests for ListCategories
func NewListCategoriesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/categories")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPrepareImageUploadRequestWithBody generates requests for PrepareImageUpload with any type of body
func NewPrepareImageUploadRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/media/image-uploads")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListNotesRequest generates requests for ListNotes
func NewListNotesRequest(server string, params *ListNotesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/notes")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.CategorySlug != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "category_slug", *params.CategorySlug, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateNoteRequest calls the generic CreateNote builder with application/json body
func NewCreateNoteRequest(server string, body CreateNoteJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateNoteRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateNoteRequestWithBody generates requests for CreateNote with any type of body
func NewCreateNoteRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/notes")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetNoteRequest generates requests for GetNote
func NewGetNoteRequest(server string, noteId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "note_id", noteId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/notes/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListPlacesRequest generates requests for ListPlaces
func NewListPlacesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/places")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewSearchNotesRequest generates requests for SearchNotes
func NewSearchNotesRequest(server string, params *SearchNotesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/search/notes")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Q != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "q", *params.Q, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.CategorySlug != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "category_slug", *params.CategorySlug, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetHealthWithResponse request
	GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthHTTPResponse, error)

	// GetReadinessWithResponse request
	GetReadinessWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetReadinessHTTPResponse, error)

	// DeleteAuthSessionWithResponse request
	DeleteAuthSessionWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*DeleteAuthSessionHTTPResponse, error)

	// GetAuthSessionWithResponse request
	GetAuthSessionWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetAuthSessionHTTPResponse, error)

	// CreateAuthSessionWithBodyWithResponse request with any body
	CreateAuthSessionWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateAuthSessionHTTPResponse, error)

	CreateAuthSessionWithResponse(ctx context.Context, body CreateAuthSessionJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateAuthSessionHTTPResponse, error)

	// CreateAuthUserWithBodyWithResponse request with any body
	CreateAuthUserWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateAuthUserHTTPResponse, error)

	CreateAuthUserWithResponse(ctx context.Context, body CreateAuthUserJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateAuthUserHTTPResponse, error)

	// GetAuthorWithResponse request
	GetAuthorWithResponse(ctx context.Context, authorId string, reqEditors ...RequestEditorFn) (*GetAuthorHTTPResponse, error)

	// ListAuthorNotesWithResponse request
	ListAuthorNotesWithResponse(ctx context.Context, authorId string, params *ListAuthorNotesParams, reqEditors ...RequestEditorFn) (*ListAuthorNotesHTTPResponse, error)

	// ListCategoriesWithResponse request
	ListCategoriesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListCategoriesHTTPResponse, error)

	// PrepareImageUploadWithBodyWithResponse request with any body
	PrepareImageUploadWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PrepareImageUploadHTTPResponse, error)

	// ListNotesWithResponse request
	ListNotesWithResponse(ctx context.Context, params *ListNotesParams, reqEditors ...RequestEditorFn) (*ListNotesHTTPResponse, error)

	// CreateNoteWithBodyWithResponse request with any body
	CreateNoteWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateNoteHTTPResponse, error)

	CreateNoteWithResponse(ctx context.Context, body CreateNoteJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateNoteHTTPResponse, error)

	// GetNoteWithResponse request
	GetNoteWithResponse(ctx context.Context, noteId string, reqEditors ...RequestEditorFn) (*GetNoteHTTPResponse, error)

	// ListPlacesWithResponse request
	ListPlacesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListPlacesHTTPResponse, error)

	// SearchNotesWithResponse request
	SearchNotesWithResponse(ctx context.Context, params *SearchNotesParams, reqEditors ...RequestEditorFn) (*SearchNotesHTTPResponse, error)
}

type GetHealthHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetHealthHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetHealthHTTPResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetReadinessHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetReadinessHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetReadinessHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetReadinessHTTPResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteAuthSessionHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *ErrorResponse
	JSON401      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r DeleteAuthSessionHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteAuthSessionHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteAuthSessionHTTPResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetAuthSessionHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CurrentSessionResponse
	JSON400      *ErrorResponse
	JSON401      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetAuthSessionHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAuthSessionHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetAuthSessionHTTPResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreateAuthSessionHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *AuthSessionResponse
	JSON400      *ErrorResponse
	JSON401      *ErrorResponse
	JSON413      *ErrorResponse
	JSON429      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r CreateAuthSessionHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateAuthSessionHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateAuthSessionHTTPResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreateAuthUserHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *AuthSessionResponse
	JSON400      *ErrorResponse
	JSON409      *ErrorResponse
	JSON413      *ErrorResponse
	JSON429      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r CreateAuthUserHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateAuthUserHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateAuthUserHTTPResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetAuthorHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PublicAuthor
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetAuthorHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAuthorHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetAuthorHTTPResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListAuthorNotesHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AuthorNotesPage
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r ListAuthorNotesHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListAuthorNotesHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListAuthorNotesHTTPResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListCategoriesHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ListCategoriesResponse
	JSON400      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r ListCategoriesHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListCategoriesHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListCategoriesHTTPResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PrepareImageUploadHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *ImageUploadReceipt
	JSON400      *ErrorResponse
	JSON401      *ErrorResponse
	JSON409      *ErrorResponse
	JSON413      *ErrorResponse
	JSON415      *ErrorResponse
	JSON429      *ErrorResponse
	JSON500      *ErrorResponse
	JSON503      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PrepareImageUploadHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PrepareImageUploadHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PrepareImageUploadHTTPResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListNotesHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ListNotesResponse
	JSON400      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r ListNotesHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListNotesHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListNotesHTTPResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreateNoteHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *Note
	JSON400      *ErrorResponse
	JSON401      *ErrorResponse
	JSON413      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r CreateNoteHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateNoteHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateNoteHTTPResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetNoteHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Note
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetNoteHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetNoteHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetNoteHTTPResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListPlacesHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ListPlacesResponse
	JSON400      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r ListPlacesHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListPlacesHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListPlacesHTTPResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type SearchNotesHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ListNotesResponse
	JSON400      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r SearchNotesHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SearchNotesHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r SearchNotesHTTPResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetHealthWithResponse request returning *GetHealthHTTPResponse
func (c *ClientWithResponses) GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthHTTPResponse, error) {
	rsp, err := c.GetHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthHTTPResponse(rsp)
}

// GetReadinessWithResponse request returning *GetReadinessHTTPResponse
func (c *ClientWithResponses) GetReadinessWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetReadinessHTTPResponse, error) {
	rsp, err := c.GetReadiness(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetReadinessHTTPResponse(rsp)
}

// DeleteAuthSessionWithResponse request returning *DeleteAuthSessionHTTPResponse
func (c *ClientWithResponses) DeleteAuthSessionWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*DeleteAuthSessionHTTPResponse, error) {
	rsp, err := c.DeleteAuthSession(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteAuthSessionHTTPResponse(rsp)
}

// GetAuthSessionWithResponse request returning *GetAuthSessionHTTPResponse
func (c *ClientWithResponses) GetAuthSessionWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetAuthSessionHTTPResponse, error) {
	rsp, err := c.GetAuthSession(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAuthSessionHTTPResponse(rsp)
}

// CreateAuthSessionWithBodyWithResponse request with arbitrary body returning *CreateAuthSessionHTTPResponse
func (c *ClientWithResponses) CreateAuthSessionWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateAuthSessionHTTPResponse, error) {
	rsp, err := c.CreateAuthSessionWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateAuthSessionHTTPResponse(rsp)
}

func (c *ClientWithResponses) CreateAuthSessionWithResponse(ctx context.Context, body CreateAuthSessionJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateAuthSessionHTTPResponse, error) {
	rsp, err := c.CreateAuthSession(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateAuthSessionHTTPResponse(rsp)
}

// CreateAuthUserWithBodyWithResponse request with arbitrary body returning *CreateAuthUserHTTPResponse
func (c *ClientWithResponses) CreateAuthUserWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateAuthUserHTTPResponse, error) {
	rsp, err := c.CreateAuthUserWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateAuthUserHTTPResponse(rsp)
}

func (c *ClientWithResponses) CreateAuthUserWithResponse(ctx context.Context, body CreateAuthUserJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateAuthUserHTTPResponse, error) {
	rsp, err := c.CreateAuthUser(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateAuthUserHTTPResponse(rsp)
}

// GetAuthorWithResponse request returning *GetAuthorHTTPResponse
func (c *ClientWithResponses) GetAuthorWithResponse(ctx context.Context, authorId string, reqEditors ...RequestEditorFn) (*GetAuthorHTTPResponse, error) {
	rsp, err := c.GetAuthor(ctx, authorId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAuthorHTTPResponse(rsp)
}

// ListAuthorNotesWithResponse request returning *ListAuthorNotesHTTPResponse
func (c *ClientWithResponses) ListAuthorNotesWithResponse(ctx context.Context, authorId string, params *ListAuthorNotesParams, reqEditors ...RequestEditorFn) (*ListAuthorNotesHTTPResponse, error) {
	rsp, err := c.ListAuthorNotes(ctx, authorId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListAuthorNotesHTTPResponse(rsp)
}

// ListCategoriesWithResponse request returning *ListCategoriesHTTPResponse
func (c *ClientWithResponses) ListCategoriesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListCategoriesHTTPResponse, error) {
	rsp, err := c.ListCategories(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListCategoriesHTTPResponse(rsp)
}

// PrepareImageUploadWithBodyWithResponse request with arbitrary body returning *PrepareImageUploadHTTPResponse
func (c *ClientWithResponses) PrepareImageUploadWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PrepareImageUploadHTTPResponse, error) {
	rsp, err := c.PrepareImageUploadWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePrepareImageUploadHTTPResponse(rsp)
}

// ListNotesWithResponse request returning *ListNotesHTTPResponse
func (c *ClientWithResponses) ListNotesWithResponse(ctx context.Context, params *ListNotesParams, reqEditors ...RequestEditorFn) (*ListNotesHTTPResponse, error) {
	rsp, err := c.ListNotes(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListNotesHTTPResponse(rsp)
}

// CreateNoteWithBodyWithResponse request with arbitrary body returning *CreateNoteHTTPResponse
func (c *ClientWithResponses) CreateNoteWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateNoteHTTPResponse, error) {
	rsp, err := c.CreateNoteWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateNoteHTTPResponse(rsp)
}

func (c *ClientWithResponses) CreateNoteWithResponse(ctx context.Context, body CreateNoteJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateNoteHTTPResponse, error) {
	rsp, err := c.CreateNote(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateNoteHTTPResponse(rsp)
}

// GetNoteWithResponse request returning *GetNoteHTTPResponse
func (c *ClientWithResponses) GetNoteWithResponse(ctx context.Context, noteId string, reqEditors ...RequestEditorFn) (*GetNoteHTTPResponse, error) {
	rsp, err := c.GetNote(ctx, noteId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetNoteHTTPResponse(rsp)
}

// ListPlacesWithResponse request returning *ListPlacesHTTPResponse
func (c *ClientWithResponses) ListPlacesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListPlacesHTTPResponse, error) {
	rsp, err := c.ListPlaces(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListPlacesHTTPResponse(rsp)
}

// SearchNotesWithResponse request returning *SearchNotesHTTPResponse
func (c *ClientWithResponses) SearchNotesWithResponse(ctx context.Context, params *SearchNotesParams, reqEditors ...RequestEditorFn) (*SearchNotesHTTPResponse, error) {
	rsp, err := c.SearchNotes(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSearchNotesHTTPResponse(rsp)
}

// ParseGetHealthHTTPResponse parses an HTTP response from a GetHealthWithResponse call
func ParseGetHealthHTTPResponse(rsp *http.Response) (*GetHealthHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParseGetReadinessHTTPResponse parses an HTTP response from a GetReadinessWithResponse call
func ParseGetReadinessHTTPResponse(rsp *http.Response) (*GetReadinessHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetReadinessHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParseDeleteAuthSessionHTTPResponse parses an HTTP response from a DeleteAuthSessionWithResponse call
func ParseDeleteAuthSessionHTTPResponse(rsp *http.Response) (*DeleteAuthSessionHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteAuthSessionHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetAuthSessionHTTPResponse parses an HTTP response from a GetAuthSessionWithResponse call
func ParseGetAuthSessionHTTPResponse(rsp *http.Response) (*GetAuthSessionHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAuthSessionHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CurrentSessionResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseCreateAuthSessionHTTPResponse parses an HTTP response from a CreateAuthSessionWithResponse call
func ParseCreateAuthSessionHTTPResponse(rsp *http.Response) (*CreateAuthSessionHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateAuthSessionHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest AuthSessionResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 413:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON413 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseCreateAuthUserHTTPResponse parses an HTTP response from a CreateAuthUserWithResponse call
func ParseCreateAuthUserHTTPResponse(rsp *http.Response) (*CreateAuthUserHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateAuthUserHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest AuthSessionResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 413:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON413 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetAuthorHTTPResponse parses an HTTP response from a GetAuthorWithResponse call
func ParseGetAuthorHTTPResponse(rsp *http.Response) (*GetAuthorHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAuthorHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PublicAuthor
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseListAuthorNotesHTTPResponse parses an HTTP response from a ListAuthorNotesWithResponse call
func ParseListAuthorNotesHTTPResponse(rsp *http.Response) (*ListAuthorNotesHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListAuthorNotesHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AuthorNotesPage
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseListCategoriesHTTPResponse parses an HTTP response from a ListCategoriesWithResponse call
func ParseListCategoriesHTTPResponse(rsp *http.Response) (*ListCategoriesHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListCategoriesHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListCategoriesResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePrepareImageUploadHTTPResponse parses an HTTP response from a PrepareImageUploadWithResponse call
func ParsePrepareImageUploadHTTPResponse(rsp *http.Response) (*PrepareImageUploadHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PrepareImageUploadHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest ImageUploadReceipt
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 413:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON413 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 415:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON415 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseListNotesHTTPResponse parses an HTTP response from a ListNotesWithResponse call
func ParseListNotesHTTPResponse(rsp *http.Response) (*ListNotesHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListNotesHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListNotesResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseCreateNoteHTTPResponse parses an HTTP response from a CreateNoteWithResponse call
func ParseCreateNoteHTTPResponse(rsp *http.Response) (*CreateNoteHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateNoteHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Note
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 413:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON413 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetNoteHTTPResponse parses an HTTP response from a GetNoteWithResponse call
func ParseGetNoteHTTPResponse(rsp *http.Response) (*GetNoteHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetNoteHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Note
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseListPlacesHTTPResponse parses an HTTP response from a ListPlacesWithResponse call
func ParseListPlacesHTTPResponse(rsp *http.Response) (*ListPlacesHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListPlacesHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListPlacesResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseSearchNotesHTTPResponse parses an HTTP response from a SearchNotesWithResponse call
func ParseSearchNotesHTTPResponse(rsp *http.Response) (*SearchNotesHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SearchNotesHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListNotesResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
